### ISSUE TITLE
Duplicate alias names generated by Relay

### ISSUE THREAD

**Issue by miracle2k** [facebook/relay#1334] opened 2016-08-11 19:20 UTC
I have relay (0.9.2) sending the following query part to my server:

```
fragment F0 on Client {
  _customers31xUfl:customers(first:50) {
    count
  },
  _customers31xUfl:customers(first:50,search:"") {
    count
  },
}
```

The server (the Python implementation), tells me: _'Fields "_customers31xUfl" conflict because they have differing arguments. Use different aliases on the fields to fetch both if this was intentional._

I know I am not posting a lot of info, but my strong guess is that Relay doesn't care to differentiate between the search variable being null and being an empty string, and this being the source of the bug.

**Comment by psalz** [comment] 2016-08-12 08:06
Yep, I can reproduce this. Definitely related to [this line in serializeCallValue](https://github.com/facebook/relay/blob/bf88f805096e99783ac130a791c4244fd7fc0b2a/src/query/serializeRelayQueryCall.js#L40).

**Comment by lucasbento** [comment] 2016-12-13 14:54
Hey @miracle2k and @psalz: did you manage to fix it somehow?

Same thing happening here with Relay 0.9.3, I still don't know how to reproduce it and also happens only sometimes.

**Comment by josephsavona** [comment] 2016-12-13 16:21
This likely occurs when the value has a falsy value (search being an empty string). To distinguish the fields, you can add an alias to one of them.

**Comment by sibelius** [comment] 2016-12-13 20:07
I've stepped in the same issue today! \o/

my scenario

I have a list of products with a search parameters on products connection

```graphql
products(first: 10, search: "awesome") {
   edges {
     node {
       id
    }
 }
}
```

Then I go to another page to add a new product using a mutation

this is the fatquery

```jsx
getFatQuery() {
    return Relay.QL`
      fragment on ProductCreatePayload {
        error
        productEdge
        viewer {
          products
        }
      }
    `;
  }
```

this will throw the error above on products, because `products(search: "$search")` is not the same as `products()`

so I've added a fragment to my mutation like this:

```js
static fragments = {
    viewer: () => Relay.QL`
      fragment on Viewer {
        id
        products(first: 10) {
          edges {
            node {
              id
            }
          }
        }
      }
    `,
  }
```

So now I have products(first: "$count") and products(first: "$count", search: "$search") and they will reconcile well

maybe this is just a hack but works for now

**Comment by sibelius** [comment] 2016-12-15 18:00
somethings it still crashes using the above approach

using the [Relay.GraphQLMutation](https://facebook.github.io/relay/docs/api-reference-relay-graphql-mutation.html#content) could solve this?

**Comment by josephsavona** [comment] 2016-12-15 18:39
Yeah, I'd recommend trying `RelayGraphQLMutation` here.

**Comment by wincent** [comment] 2017-01-31 01:21
This hasn't seen any activity for a while so I am going to close it optimistically on the assumption that the workarounds mentioned above (aliasing and using `Relay.GraphQLMutation`) have been sufficient to resolve the issue. If this is incorrect, or anybody thinks they've run into a new bug, please do file another issue.

Thanks for your contribution!

**Closed by wincent** 2017-01-31 01:21 UTC

**Comment by AnderssonChristian** [comment] 2017-05-18 12:41
I can confirm that adding an alias did solve the problem for me.

**Comment by wincent** [comment] 2017-05-18 21:56
Thanks for looping back, @AnderssonChristian.
