### ISSUE TITLE
relay compiler breaks when trying to run inside a docker 

### ISSUE THREAD

**Issue by daniloab** [facebook/relay#3939] opened 2022-06-04 17:25 UTC
I'm trying to build a docker image with a nextjs + relay app.

When building the image I install the dependencies and run the build command. The build command has a prebuild command responsible to run the relay compiler.

When trying to build the image following the steps above returns the error of platform not supported by the relay-compiler.

<img width="986" alt="Screen Shot 2022-06-04 at 13 54 04" src="https://user-images.githubusercontent.com/19939822/172018315-c5e17625-58e1-4afd-8d4c-22fbaab6b1c0.png">

Here is an example of the repository with this error happening.

## Steps to reproduce:
- 1. `git clone git@github.com:daniloab/relay-13-nextjs.git`
- 2. `yarn` 
- 3. `docker build -t relay-13-nextjs-image .`

and should return the same error:
<img width="1440" alt="Screen Shot 2022-06-04 at 14 22 52" src="https://user-images.githubusercontent.com/19939822/172018384-0d8e2dca-5bf0-481d-be04-71fbe4d3220f.png">

would I be failing to set some platform configuration?

## environment
os: macOS Big Sur 11.6 [MacBook m1]
relay: 13.2.0
node: v16.13.2

**Comment by soneymathew** [comment] 2022-06-05 05:45
@daniloab Does you process.platform and process.arch return [these supported values](https://github.com/facebook/relay/blob/5e3c7b6d4f41461a1a6a59d3373d519ad9a0856d/packages/relay-compiler/index.js#L18-L31)?

**Comment by geniyong** [comment] 2022-06-07 02:44
@daniloab, @soneymathew 
The supported platform values are in `main` branch but @daniloab  you are in `relay: 13.2.0` version.
New version is not released yet, including m1 supported platform codes (it's added after 13.2 release).

So could you try to use `main` branch code ? (not `13.2.0` version)

**Comment by daniloab** [comment] 2022-06-07 13:41
> @daniloab Does you process.platform and process.arch return [these supported values](https://github.com/facebook/relay/blob/5e3c7b6d4f41461a1a6a59d3373d519ad9a0856d/packages/relay-compiler/index.js#L18-L31)?

Yes, avoiding run relay compiler command and get into the image the process is this one below:

<img width="215" alt="Screen Shot 2022-06-07 at 10 39 53" src="https://user-images.githubusercontent.com/19939822/172394761-d431555a-c48e-4551-b021-d386b993bbe6.png">

The best resolution is building the app before sending it to the container. But once the error was caught I found it interesting to open a question

**Comment by bencoveneyttl** [comment] 2022-07-08 15:59
Experiencing the same problem on a similar set up:

- os: macOS Monterey 12.4 [MacBook m1]
- relay: 13.2.0
- node: v14.19.2
- `process.platform`: linux
- `process.arch`: arm64

My use case is using VSCode devcontainers - specifically the container `mcr.microsoft.com/vscode/devcontainers/typescript-node:dev-14-bullseye`.

**Comment by bencoveneyttl** [comment] 2022-07-08 16:01
Looks like this might be a duplicate of #3799

**Closed** 2022-07-08 18:35 UTC
