### ISSUE TITLE
[rust-compiler] Constant Custom Scalars unsupported?

### ISSUE THREAD

**Issue by tbezman** [facebook/relay#3764] opened 2022-01-19 01:24 UTC
## Description

Looks like there's an issue with supplying constant values to a variable where a custom scalar is accepted.

I have a very simple repro repo at https://github.com/tbezman/relay-scalar-bug-repro.

Instructions to reproduce:
```
cd relay-scalar-bug-repro;
yarn install;
yarn relay-compiler;
```

## Files at a glance

schema.graphql
```graphql
scalar DateTime

type Query {
    testCustomScalarField(time: DateTime): String
}
```

relay.config.js
```js
module.exports = {
  src: "./",
  schema: "schema.graphql",
  language: "typescript",
  customScalars: {
    DateTime: "String",
  },
};
```

TestPage.tsx
```tsx
graphql`
    query TestPageQuery {
        testCustomScalarField(time: "Some Constant String")
    }
`
```

## Erroneous Output

Output from `yarn relay-compiler`
```
querying files to compile...
[default] compiling...
[ERROR] ✖︎ Unsupported (user-defined) scalar type 'DateTime'

  src/TestPage.tsx:3:37
    2 │     query TestPageQuery {
    3 │         testCustomScalarField(time: "Some Constant String")
      │                                     ^^^^^^^^^^^^^^^^^^^^^^
    4 │     }

[ERROR] Compilation failed.
[ERROR] Failed to build:
 - Validation errors:
 - Unsupported (user-defined) scalar type 'DateTime':src/TestPage.tsx:63:85
```

**Comment by tbezman** [comment] 2022-01-19 01:25
@captbaritone This isn't super high priority. Our temporary workaround is to use variables instead of constant strings and pass the value from the JS side.

**Comment by alunyov** [comment] 2022-01-19 01:42
Thanks for the report! This is a duplicate of the https://github.com/facebook/relay/issues/3730. 
I'm closing this for now, to keep the discussion in the initial issue.

**Closed by alunyov** 2022-01-19 01:42 UTC
