### ISSUE TITLE
[modern] 1.3 Doesn't compile in React Native

### ISSUE THREAD

**Issue by vshab** [facebook/relay#2074] opened 2017-08-30 10:12 UTC
After upgrading from 1.2 to 1.3 i've got this error when building the project:
```
error: 
bundling failed: "TransformError: /Users/vladslavshabanov/projects/project/node_modules/relay-debugger-react-native-runtime/lib/index.js: 
[BABEL] /Users/vladslavshabanov/projects/project/node_modules/relay-debugger-react-native-runtime/lib/index.js: 
Unknown option: /Users/vladslavshabanov/projects/project/node_modules/react/index.js.Children. 
Check out http://babeljs.io/docs/usage/options/ for more information about options.\n\nA common cause of this error is the presence of a configuration options object without the corresponding preset name. 
Example:\n\nInvalid:\n  `{ presets: [{option: value}] }`\nValid:\n  `{ presets: [['presetName', {option: value}]] }`\n\nFor more detailed information on preset configuration, please see http://babeljs.io/docs/plugins/#pluginpresets-options. 
(While processing preset: \"/Users/vladslavshabanov/projects/project/node_modules/react/index.js\")"
```

I suspect that issues is introduced by 87b5a9a

**Comment by ngthorg** [comment] 2017-08-30 10:26
me too 💬

**Comment by corasan** [comment] 2017-08-30 18:56
Getting the same error now

**Comment by Oxyaction** [comment] 2017-09-01 10:12
Having the same problem, looks like babel presets, specified in
`node_modules/relay-debugger-react-native-runtime/.babelrc` are not installed,
after adding them manually
 `yarn add -D babel-preset-react babel-preset-stage-0 babel-preset-es2015` 
compiles fine, my `.babelrc`:
```
{
  "plugins": [
    "relay"
  ],
  "presets": [
    "react-native"
  ]
}
```
`babel-plugin-relay` **1.3.0**
`react-relay` **1.3.0**
`relay-compiler` **1.3.0**

**Comment by saudpunjwani101** [comment] 2017-09-01 12:42
Doesn't work for me

**Comment by fi11** [comment] 2017-09-01 12:43
+1 me too

**Comment by saudpunjwani101** [comment] 2017-09-01 13:34
Well it works now. Did the following

yarn add -D babel-preset-react babel-preset-stage-0 babel-preset-es2015

then restart your packager

**Comment by Oxyaction** [comment] 2017-09-01 13:37
👍 edited my comment

**Comment by corasan** [comment] 2017-09-01 14:56
@Oxyaction that worked! 👍

**Comment by mzbyszynski** [comment] 2017-09-01 15:49
I don't think `relay-debugger-react-native-runtime` is open source yet, but it seems like the issue is that these packages:
* `babel-preset-react`
* `babel-preset-stage-0`
* `babel-preset-es2015`

Need to be listed as `dependencies` and not `devDependencies` in the `relay-debugger-react-native-runtime`.

@Slava I believe you are/have worked on `relay-debugger-react-native-runtime`. Does this fix make sense to you?

**Comment by kassens** [comment] 2017-09-01 18:44
We should figure out why those babel presets are required and fix that instead of adding them as dependencies.

**Comment by Slava** [comment] 2017-09-02 23:59
@kassens I no longer have access to the source. I remember moving `.babelrc` into `src` folder for the `relay-debugger-react-native-runtime` so it doesn't get picked up by babel when the `lib` folder is imported. I thought that would help but either I didn't publish that version to npm or it didn't do the trick.

**Comment by leebyron** [comment] 2017-09-11 22:08
I'll work on fixing this soon for the next Relay release

**Comment by marc314** [comment] 2017-09-13 16:46
+1

**Comment by vshab** [comment] 2017-09-22 10:39
Seems to be fixed in 1.4. 
Thanks!

**Comment by sibelius** [comment] 2017-09-25 12:23
@vshab can we close this?

**Comment by vshab** [comment] 2017-09-25 12:46
@sibelius i think yes. Can't reproduce in 1.4

**Comment by sibelius** [comment] 2017-09-25 12:49
close them

**Closed** 2017-09-26 08:42 UTC
Labels: bug
