### ISSUE TITLE
Local cache issue. Reproducible on Todo example.

### ISSUE THREAD

**Issue by r0b1n** [facebook/relay#871] opened 2016-02-23 13:00 UTC
Looks like there is some issues with handling local cache together with filtering.
After changing records field which participates in filtration Relay doesn't re-filter lists and item remains in old list, not appears in right list.
After page reloading everything becomes normal, it means data on server side is ok.

Gif with error on todo example: 
After unchecking "Taste Javascript" remains in Completed list, and not moved to "Active"
![relaybug-2](https://cloud.githubusercontent.com/assets/548774/13252193/fa47b9b4-da3d-11e5-98f4-90912b955bd5.gif)

**Comment by josephsavona** [comment] 2016-02-23 18:22
Thanks for reporting this. It looks like the range configs need to be updated so that modifying a todo's completed status also adds/removes it to the appropriate active/completed lists.

**Comment by josephsavona** [comment] 2016-02-24 00:24
Closing as a duplicate of #873

**Closed by josephsavona** 2016-02-24 00:24 UTC
Labels: good first bug, help wanted
