### ISSUE TITLE
[Modern] Subscriptions and live queries docs and examples

### ISSUE THREAD

**Issue by ivosabev** [facebook/relay#1655] opened 2017-04-20 14:31 UTC
The docs claim that Relay supports subscriptions and live queries, but there are no examples provided or documentation.

> GraphQL Subscriptions & Live Queries
> Relay Modern supports GraphQL Subscriptions, using the imperative update API to allow modifications to the store whenever a payload is received. It also features experimental support for GraphQL Live Queries via polling.

https://facebook.github.io/relay/docs/new-in-relay-modern.html#graphql-subscriptions-live-queries

**Comment by irrigator** [comment] 2017-05-01 03:17
The todo-modern example helps me a lot when I am learning the modern relay API. I think it's a perfect candidate for showing GraphQL subscription capabilities.

**Comment by JenniferWang** [comment] 2017-05-01 15:57
Subscription and live query require a different server side support from normal GraphQL query/mutation. Relay supports the semantics/API but it relies you to give the actual server side support.
https://github.com/facebook/relay/blob/d94380a9be64f2a72828effdb0c934ef9bf74aff/packages/relay-compiler/core/__tests__/fixtures/flow-generator/roots.input.rql#L19-L25
https://github.com/facebook/relay/blob/15a7ebb5d87f8aae3d1a23ed0cac15f1eff5714e/packages/relay-runtime/subscription/requestRelaySubscription.js#L21-L28

If your server supports subscription, you could pass the subscription function here https://github.com/facebook/relay/blob/88d09dcc30f851d8d9abd696d686eb9683b56ba6/packages/relay-runtime/network/RelayNetwork.js#L41.
```
// subscription API looks similar to Mutation
// use ` const requestSubscription = require('RelayModern')`
export type GraphQLSubscriptionConfig = {|
  subscription: GraphQLTaggedNode,
  variables: Variables,
  onCompleted?: ?() => void,
  onError?: ?(error: Error) => void,
  onNext?: ?(response: ?Object) => void,
  updater?: ?(store: RecordSourceSelectorProxy) => void,
|};
```
For live query, Relay currently supports polling-based 'live' query. You could specify a poll interval in the cache configure https://github.com/facebook/relay/blob/88d09dcc30f851d8d9abd696d686eb9683b56ba6/packages/react-relay/classic/environment/RelayCombinedEnvironmentTypes.js#L25

**Comment by jamesone** [comment] 2017-05-17 02:30
Is there an example we could find somewhere that implements subscriptions using relay modern?

**Comment by jamesone** [comment] 2017-05-24 00:49
Any updates on finding an example that uses relay modern subscriptions? Would be super super handy to have an example we could all checkout 😃

**Comment by mattkrick** [comment] 2017-05-24 00:54
https://facebook.github.io/relay/docs/subscriptions.html

**Comment by ivosabev** [comment] 2017-05-24 09:10
The same thing for Live Queries would be appreciated.

**Comment by jamesone** [comment] 2017-05-31 10:20
@JenniferWang Is there any chance you could track down the Environment object displayed here: https://facebook.github.io/relay/docs/subscriptions.html That'd be super awesome :)

**Comment by macolsson** [comment] 2017-06-01 14:27
[Question on SO](https://stackoverflow.com/questions/44284997/relay-modern-connecting-websocket-to-network-layer)

I'm wondering the same. I'm interested in seeing a working example/snippet of Relay Modern Subscriptions using a websocket.

As seen in the link, I've worked up an example that can accept a subscription through the `requestSubscription` that operates with my custom NetworkLayer. The NetworkLayer successfully sends a request to the server (implemented in Graphene-python) and is able to generate responses:

```
// Create a websocket instance.
const subscriptionWebSocket = new ReconnectingWebSocket('ws://example.com/ws/subscriptions/', null, options);

// Define subscribe function to be used in the NetworkLayer.
function subscriptionHandler(subscriptionConfig, variables, cacheConfig, observer) {
  subscriptionWebSocket.send(JSON.stringify(subscriptionConfig.text));
  return { dispose: () => null };
}

// Create a new NetworkLayer.
const network = Network.create(fetchQuery, subscriptionHandler);

// Create subscription query.
const subscription = graphql`
  subscription mainSubscription {
    testData {
      anotherNode {
        data
      }
    }
  }
`;

// Create subscription request with config and above query.
requestSubscription(
  environment,
  {
    subscription,
    variables: {},
    onComplete: () => { /* What goes here? Never called. */ },
    onNext: () => { /* What goes here? Never called. */ },
    onError: () => { /* What goes here? Never called. */ },
  },
);
```

The issue is that I have no idea how to connect a websocket to receive the servers response, and later parsing the response into the Relay Modern Store.

**Comment by JenniferWang** [comment] 2017-06-01 18:55
@jamesone the `Environment` is usually the `RelayModernEnvironment` or you customized environment.

**Comment by JenniferWang** [comment] 2017-06-01 20:07
@macolsson Just like `fetch` method, it is the `subscriptionHandler`s responsibility to call `onNext`, etc. It needs a subscribe-publish mechanism so I don't know if `ReconnectingWebSocket` could fulfill this role.

**Comment by macolsson** [comment] 2017-06-01 20:11
@JenniferWang Thanks for the pointer. I'll look to revise the websocket logic.

I've been looking at using the OnNext method from the observer, however I'm not able to figure out exactly what I'm supposed to call it with;
I've tried adding a new source (RecordSource); this threw an error which I was unable to decode, is it supposed to use the same source as the NetworkLayer?

Are there are example structures that I could follow? Not sure I can fully recreate based on Flow.

**Comment by JenniferWang** [comment] 2017-06-01 20:27
@macolsson You should definitely look at the Flow type. I don't know if we have example implementation of a `subscribe` function. But you should look at `RelayNetwork#requestStream`.

**Comment by josephsavona** [comment] 2017-06-01 20:30
iirc the subscription handler should call onNext with the payload received from the server, the object with `{data, errors?}`

**Comment by macolsson** [comment] 2017-06-01 20:47
@JenniferWang I've followed the `environment#SendSubscription` function called from the `requestSubscription` into `Network#requestStream`. Seems to be the way to go.

@josephsavona Seems like that would be something to try; [source](https://github.com/facebook/relay/blob/391ca8e10f837a688ece90a204b471c1b0fae3a4/packages/relay-runtime/network/RelayNetwork.js#L217) I'll give it a go!

**Comment by macolsson** [comment] 2017-06-02 07:54
@josephsavona Your recollection was indeed accurate. I have the below code which gets validated and accepted in the onNext call-chain:

```
function subscriptionHandler(subscriptionConfig, variables, cacheConfig, observer) {
  observer.onNext({
    data: { testData: { id: 'y', anotherNode: { id: 'z', data: 'x' } } },
    errors: [],
  });
  return {
    dispose: () => null,
  };
}
```

So that part seems to work great! However, the data does not get updated; am I required to build my own `requestSubscription#updater`, or am I missing something here?

**Comment by josephsavona** [comment] 2017-06-02 08:16
@macolsson Hmm, the first thing I would check is that the data matches up with the subscription itself. For mutations ansnsubscriptions, records with an `id` should update automatically - an updated is generally only needed for things like connections or records that don't have an id.

**Comment by macolsson** [comment] 2017-06-02 08:24
@josephsavona Of course! I had some silly test data in the response. I've updated the faked server response to match the initial response from the GraphQL server. It seems to work great.

Thank you for all your help!

**Comment by jamesone** [comment] 2017-06-02 08:25
@macolsson Hey when you've got a working copy of your subscriptions network layer? Would you mind sharing it?

**Comment by josephsavona** [comment] 2017-06-02 08:29
Share as a PR to the docs! ;-)

**Comment by macolsson** [comment] 2017-06-02 09:25
@jamesone Will do.

@josephsavona I'll see what we can do!

**Comment by macolsson** [comment] 2017-06-05 12:44
ping @jamesone @josephsavona 

I’ll just write down how I’ve approached this issue after the assistance found in this thread. It might be usable for someone else. If anyone has any comments, suggestions or anything on the below code or reasoning, do let me know. I tried adding some comments when writing the code, hope some of it makes sense.

Firstly I built a `SubscriptionHandler` that will be referenced from the `requestStream#subscribeFunction` (`SubscriptionHandler#setupSubscription`).

The `SubscriptionHandler` instantiates a WebSocket (using a custom version of ReconnectingWebSockets) and attaches the onmessage event to an internal method (`SubscriptionHandler#receiveSubscriptionPayload`) which will add the payload to the corresponding subscription.

We create new subscriptions through `SubscriptionHandler#newSubscription` which will use the internal attribute `SubscriptionHandler.subscriptions` to add a keyed entry of this subscription (we use an MD5-hash util over the query and variables); meaning the object will come out as:
```
SubscriptionHandler.subscriptions = {
  [md5hash]: {
    query: QueryObject,
    variables: SubscriptionVariables,
    observer: Observer (contains OnNext method)
}
```

Whenever the server sends a subscription response the `SubscriptionHandler#receiveSubscriptionPayload` method will be called and it will identify what subscription the payload belongs to by using the query/variables md5 hash, then use the `SubscriptionHandler.subscriptions` observer onNext method.

This approach requires the server to return a message such as:
```
export type ServerResponseMessageParsed = {
  payload: QueryPayload,
  request: {
    query: string,
    variables: Object,
  }
}
```

I do not know if this is a great way of handling subscriptions, but it works for now with my current setup.

This is doable because the method passed into the network subscription function will handle all interactions through the SubscriptionHandler.

Some code:

**NetworkLayer**
```
function fetchQuery(operation, variables) {
  return fetch('/graphql', {
    method: 'POST',
    headers: {
      credentials: 'same-origin',
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      query: operation.text,
      variables,
    }),
  }).then((response) => response.json());
}

const network = Network.create(
  fetchQuery,
  subscriptionHandler.setupSubscription,
);
const source = new RecordSource();
const store = new Store(source);
const environment = new Environment({ network, store });

// Attach the newly created environment to the subscription handler.
subscriptionHandler.attachEnvironment(environment);
```

**SubscriptionHandler.js**
```
class SubscriptionHandler {
  subscriptions: Object;
  subscriptionEnvironment: RelayModernEnvironment;
  websocket: Object;

  /**
   * The SubscriptionHandler constructor. Will setup a new websocket and bind
   * it to internal method to handle receving messages from the ws server.
   *
   * @param  {string} websocketUrl      - The WebSocket URL to listen to.
   * @param  {Object} webSocketSettings - The options object.
   *                                      See ReconnectingWebSocket.
   */
  constructor(websocketUrl: string, webSocketSettings: WebSocketSettings) {
    // All subscription hashes and objects will be stored in the
    // this.subscriptions attribute on the subscription handler.
    this.subscriptions = {};

    // Store the given environment internally to be reused when registering new
    // subscriptions. This is required as per the requestRelaySubscription spec
    // (method requestSubscription).
    this.subscriptionEnvironment = null;

    // Create a new WebSocket instance to be able to receive messages on the
    // given URL. Always opt for default protocol for the RWS, second arg.
    this.websocket = new ReconnectingWebSocket(
      websocketUrl,
      null,  // Protocol.
      webSocketSettings,
    );

    // Bind an internal method to handle incoming messages from the websocket.
    this.websocket.onmessage = this.receiveSubscriptionPayload;
  }

  /**
   * Method to attach the Relay Environment to the subscription handler.
   * This is required as the Network needs to be instantiated with the
   * SubscriptionHandler's methods, and the Environment needs the Network Layer.
   *
   * @param  {Object} environment - The apps environment.
   */
  attachEnvironment = (environment: RelayModernEnvironment) => {
    this.subscriptionEnvironment = environment;
  }

  /**
   * Generates a hash from a given query and variable pair. The method
   * used is a recreatable MD5 hash, which is used as a 'key' for the given
   * subscription. Using the MD5 hash we can identify what subscription is valid
   * based on the query/variable given from the server.
   *
   * @param  {string} query     - A string representation of the subscription.
   * @param  {Object} variables - An object containing all variables used
   *                              in the query.
   * @return {string}             The MD5 hash of the query and variables.
   */
  getHash = (query: string, variables: HashVariables) => {
    const queryString = query.replace(/\s+/gm, '');
    const variablesString = JSON.stringify(variables);
    const hash = md5(queryString + variablesString).toString();
    return hash;
  }

  /**
   * Method to be bound to the class websocket instance. The method will be
   * called each time the WebSocket receives a message on the subscribed URL
   * (see this.websocket options).
   *
   * @param  {string} message - The message received from the websocket.
   */
  receiveSubscriptionPayload = (message: ServerResponseMessage) => {
    const response: ServerResponseMessageParsed = JSON.parse(message.data);
    const { query, variables } = response.request;
    const hash = this.getHash(query, variables);

    // Fetch the subscription instance from the subscription handlers stored
    // subscriptions.
    const subscription = this.subscriptions[hash];

    if (subscription) {
      // Execute the onNext method with the received payload after validating
      // that the received hash is currently stored. If a diff occurs, meaning
      // no hash is stored for the received response, ignore the execution.
      subscription.observer.onNext(response.payload);
    } else {
      console.warn(`Received payload for unregistered hash: ${hash}`);
    }
  }

  /**
   * Method to generate new subscriptions that will be bound to the
   * SubscriptionHandler's environment and will be stored internally in the
   * instantiated handler object.
   *
   * @param {string} subscriptionQuery - The query to subscribe to. Needs to
   *                                     be a validated subscription type.
   * @param {Object} variables         - The variables for the passed query.
   * @param {Object} configs           - A subscription configuration. If
   *                                     override is required.
   */
  newSubscription = (
      subscriptionQuery: GraphQLTaggedNode,
      variables: Variables,
      configs: GraphQLSubscriptionConfig,
  ) => {
    const config = configs || DEFAULT_CONFIG;

    requestSubscription(
      this.subscriptionEnvironment,
      {
        subscription: subscriptionQuery,
        variables: {},
        ...config,
      },
    );
  }

  setupSubscription = (
    config: ConcreteBatch,
    variables: Variables,
    cacheConfig: ?CacheConfig,
    observer: Observer,
  ) => {
    const query = config.text;

    // Get the hash from the given subscriptionQuery and variables. Used to
    // identify this specific subscription.
    const hash = this.getHash(query, variables);

    // Store the newly created subscription request internally to be re-used
    // upon message receival or local data updates.
    this.subscriptions[hash] = { query, variables };

    const subscription = this.subscriptions[hash];
    subscription.observer = observer;

    // Temp fix to avoid WS Connection state.
    setTimeout(() => {
      this.websocket.send(JSON.stringify({ query, variables }));
    }, 100);
  }
}

const subscriptionHandler = new SubscriptionHandler(WS_URL, WS_OPTIONS);

export default subscriptionHandler;
```

**Comment by josephsavona** [comment] 2017-06-05 22:14
The main thing that stands out is that the server shouldn't have to send the query/variables back in every response. Instead, you can send a unique identifier for the query as part of the initial message to the server, then have the server just send back GraphQL payload + that identifier. A simple increment if integer would work for that. It would also avoid the overhead of getHash().

**Comment by jamesone** [comment] 2017-06-05 23:35
Awesome, I'll have a play around with it soon! @macolsson Just out of curiosity, what are you using subscriptions for?

**Comment by macolsson** [comment] 2017-06-06 06:57
@josephsavona We're currently using the hash to store the query/variables in the backend, so that we can at any time run a query and return the results of this query to every single client that is listening to the query/variable pairs. The has is currently used to key the cache-store in the back-end as well, as was initially thought as an extra layer of validation; send q/v and hash, compare, receive q/v and hash, compare. But it might be redundant. We're still looking into different approaches.

@jamesone We'll be using it to update multiple clients on data mutation (not just the client who performs the mutation) and we're using it to stream  real-time data from hardware to mobile app to backend.

**Comment by bochen2014** [comment] 2017-06-15 07:37
I've managed to get it work.  you can try  [here](http://relay-modern.azurewebsites.net/)
open 2 browser window and change todo status in one, the other will get updated automatically..

**Comment by sibelius** [comment] 2017-06-16 01:26
@bochen2014 are you gonna open source your work any time soon?

**Comment by nikolasburk** [comment] 2017-06-22 15:56
I just managed to make subscriptions work with Relay Modern as well. Note that I'm not using `WebSocket` but the `SubscriptionClient` that can be found in [`subscriptions-transport-ws`](https://github.com/apollographql/subscriptions-transport-ws) to manage the connection to the server.

Here's my minimal setup code:

### Environment.js

```js
import { SubscriptionClient } from 'subscriptions-transport-ws'
const {
  Environment,
  Network,
  RecordSource,
  Store,
} = require('relay-runtime')
const store = new Store(new RecordSource())


const fetchQuery = (operation, variables) => {
  return fetch('https://api.graph.cool/relay/v1/__GRAPHCOOL_PROJECT_ID__', {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      query: operation.text,
      variables,
    }),
  }).then(response => {
    return response.json()
  })
}

const websocketURL = 'wss://subscriptions.graph.cool/v1/__GRAPHCOOL_PROJECT_ID__'

function setupSubscription(
  config,
  variables,
  cacheConfig,
  observer,
) {
  const query = config.text

  const subscriptionClient = new SubscriptionClient(websocketURL, {reconnect: true})
  const id = subscriptionClient.subscribe({query, variables}, (error, result) => {
    observer.onNext({data: result})
  })
}

const network = Network.create(fetchQuery, setupSubscription)
const environment = new Environment({
  network,
  store,
})

export default environment
```

### NewLinkSubscription.js

```js
import {
  graphql,
  requestSubscription
} from 'react-relay'
import environment from '../Environment'

const newLinkSubscription = graphql`
  subscription NewLinkSubscription {
    Link {
      mutation
      node {
        id
        description
        url
        createdAt
        postedBy {
          id
          name
        }
      }
    }
  }
`

export default (onNext, onError, onCompleted, updater) => {

  const subscriptionConfig = {
    subscription: newLinkSubscription,
    variables: {},
    onError,
    onNext,
    onCompleted,
    updater
  }

  requestSubscription(
    environment,
    subscriptionConfig
  )

}
```

Now you can simply use the exported function to subscribe. For example, in one of my React components in `componentDidMount` I can now do the following:

```js
componentDidMount() {
  NewLinkSubscription(
    response => console.log(`Received data: `, response),
    error => console.log(`An error occurred:`, error),
    () => console.log(`Completed`)
  )
}
```

**Comment by hkjorgensen** [comment] 2017-07-20 23:21
@nikolasburk thanks, this is great!
How does your local `schema.graphql` file look like? I can see that you use graph.cool and the Relay endpoint schema does not include any subscriptions definitions. The `wss` one does come with subscriptions definitions, but it's not Relay compatible.

**Comment by josephsavona** [comment] 2017-07-20 23:51
@nikolasburk Care to submit a PR to document that approach?

**Comment by nikolasburk** [comment] 2017-07-21 07:55
@hkjorgensen Great point about the schema file! You're right that our Relay API currently doesn't support subscriptions. What I did to satisfy the Relay Compiler was actually manually copying over the `Subscription` type from the Simple API schema to the Relay API schema. This is still not ideal since the types of the two different APIs don't match up so you have to do some more manual work inside the app to convert the types you get from the subscription (which are from the Simple API) to the types you're using in your app (the ones from the Relay API). We're actually going to add the [Subscriptions chapter for How to GraphQL](https://www.howtographql.com/react-relay/7-subscriptions/) very soon where this approach will be explained in more detail. 

@josephsavona Will do that soon!

**Comment by idris** [comment] 2017-08-15 19:57
Perhaps this should be split into two tickets: one for live queries, one for subscriptions.

I have a live query question though:
The `poll` attribute of `cacheConfig` is only used in `streamQuery`, but not in `sendQuery`.  How do we configure Relay Modern to use `streamQuery` instead of `sendQuery`?

**Comment by josephsavona** [comment] 2017-08-15 23:11
@idris Relay Modern uses `streamQuery` by default (e.g. for `QueryRenderer`, `PaginationContainer`, etc).

**Comment by Tocknicsu** [comment] 2017-08-31 12:02
@nikolasburk
Do you have a good idea `unsubscribe`?
I have multiple component subscribe different things. But I want to unsubscribe when they are unmounted. I have no idea return the `id` to the component.

**Comment by leebyron** [comment] 2017-09-11 20:06
Check out https://facebook.github.io/relay/docs/subscriptions.html which explains `requestSubscription`. That function returns a Disposable which can `dispose()` to unsubscribe.

Also as an update, all networks now accept `Observable` as a result, which means any network can provide a "live query" style behavior.

I'm closing this issue since it's quite old, but if anyone would like to contribute to the documentation, we're always interested in reviewing those PRs.

**Closed by leebyron** 2017-09-11 20:06 UTC

**Comment by bochen2014** [comment] 2017-09-12 01:18
i did [this](http://relay-modern.azurewebsites.net/)  3 month ago ( source code [here](https://github.com/bochen2014/relay-todo-modern) as a relay live query example. you can open 2 browsers and operations there are always synced. 

the kudo should go to @taion 's [work](https://github.com/taion/graphql-relay-subscription) though, as there isn't too much front end coding involved -- the tricky part is implementing a backend that can support subscriptions

**Comment by sw-yx** [comment] 2017-10-12 09:36
the guys at graphcool also have this tutorial up: <https://www.howtographql.com/react-apollo/8-subscriptions/> just sharing for future people who find this

**Comment by jalalat** [comment] 2017-11-18 13:47
@nikolasburk subscriptionClient.subscribe is no longer a function: https://github.com/apollographql/subscriptions-transport-ws/pull/261

Do you know how to fix that?

**Comment by nikolasburk** [comment] 2017-11-19 14:01
I havent' tried it myself but I believe it should be possible to replace the `SubscriptionClient` with a [`WebSocketLink`](https://github.com/apollographql/apollo-link/tree/master/packages/apollo-link-ws) to get it to work. @jalalat

**Comment by slaviczavik** [comment] 2017-11-20 14:04
@nikolasburk It don't work me, can you please post a code here?

**Comment by slaviczavik** [comment] 2017-11-20 23:31
According to docs we can use `SubscriptionClient` like this.

```js
const subscriptionClient = new SubscriptionClient(websocketUrl, {reconnect: true})

subscriptionClient.request({ query, variables }).subscribe((
  observerOrNext, onError, onComplete
) => {
  // Make this better!
  observer.onNext(observerOrNext)
})
```

Just now I'm trying make this work, `observerOrNext` contains data, but Relay subscription is not triggered. Any suggestions?

**Comment by slaviczavik** [comment] 2017-11-21 15:43
According to [docs ](https://github.com/apollographql/subscriptions-transport-ws)we can use the `SubscriptionClient` like this.

```js
const subscriptionClient = new SubscriptionClient(websocketUrl, {reconnect: true})

const onNext = (result) => {
  observer.onNext(result)
}

const onError = (error) => {
  // Do sth on error
}

const onComplete = () => {
  // Do sth on complete
}

const client = subscriptionClient
  .request({ query, variables })
  .subscribe(onNext, onError, onComplete)
```

**Comment by perrosnk** [comment] 2017-12-07 09:55
@slaviczavik Where are you pulling the observer from?

**Comment by slaviczavik** [comment] 2017-12-07 12:48
@perrosnk It was response on @nikolasburk code.

This is full code:
```js
import { Environment, Network, RecordSource, Store } from 'relay-runtime'
import { SubscriptionClient } from 'subscriptions-transport-ws'

const endpoint = 'http://your-endpoint:3000/graphql'
const websocketUrl = 'ws://your-endpoint:3000/subscriptions'

const setupSubscription = (config, variables, cacheConfig, observer) => {
  const query = config.text

  const subscriptionClient = new SubscriptionClient(websocketUrl, {reconnect: true})

  const onNext = (result) => {
    observer.onNext(result)
  }

  const onError = (error) => {
    observer.onError(error)
  }

  const onComplete = () => {
    observer.onCompleted()
  }

  const client = subscriptionClient.request({ query, variables }).subscribe(
    onNext,
    onError,
    onComplete
  )

  // client.unsubscribe()
}

const fetchQuery = (operation, variables, cacheConfig, uploadebles) => {
  return fetch(endpoint, {
    method: 'POST',
    credentials: 'include',
    headers: {
      'content-type': 'application/json'
    },
    body: JSON.stringify({
      query: operation.text,
      variables
    })
  }).then(response => {
    return response.json()
  })
}

const network = Network.create(
  fetchQuery,
  setupSubscription
)
const source = new RecordSource()
const store = new Store(source)

const environment = new Environment({
  network,
  store
})

export default environment
```

**Comment by jeremy-colin** [comment] 2018-01-23 16:25
SubscriptionClient has been removed from the latest versions 'subscriptions-transport-ws'.
If anyone is also stumbling accross this issue, I have a working example from a fork of relay-examples here: https://github.com/jeremy-colin/relay-examples-subscription
It is still imperfect but it shows how to glue everything together

**Comment by taion** [comment] 2018-01-23 17:07
I’m pretty sure it’s still there.

**Comment by jeremy-colin** [comment] 2018-01-23 17:19
Yes excuse my shortcut, SubscriptionManager support has been removed which broke the previous implementations proposed in this thread.
