### ISSUE TITLE
queryCache module-wide variables leaking memory on the server side

### ISSUE THREAD

**Issue by fabiosantoscode** [facebook/relay#754] opened 2016-01-20 00:12 UTC
Using isomorphic-relay to get relay to work on the server, and using a load testing tool to create repeated requests and find a memory leak in an application I'm building, I observed that 2 maps called queryCache were growing unbounded.

These maps are in getRelayQueries.js, and in buildRQL.js, and they grow to thousands of keys over 600 requests to a page I have with no less than 2 containers.

Longer explanation in:

https://github.com/facebook/relay/pull/683#issuecomment-173021689

I'll do my best to provide an example if it's necessary to reproduce the issue.

**Comment by denvned** [comment] 2016-01-20 07:42
Hi @fabiosantoscode. Do your testing app recreates containers on each request using `Relay.createContainer(...)`? I can't see any other reason for such `queryCache.size` growth (well, probably except some bug in core-js polyfill for `Map`).

**Comment by fabiosantoscode** [comment] 2016-01-20 08:08
Hello! Yes it does. Since the app is wrapped in react-router and
react-router itself needs a history object which changes for every URL,
we've created an isomorphic function that creates the entire thing.

**Comment by rodrigopr** [comment] 2016-07-15 04:21
Hi, I'm facing the same behavior in our app. 
Is it reasonable to disable the `queryCache` and `fragmentCache` on the server?

I could try change how the react-router-relay create the routers if this makes more sense, but don't seem to be a simple change after a quick [look](https://github.com/relay-tools/react-router-relay/blob/master/src/QueryAggregator.js#L28-L118)

**Comment by josephsavona** [comment] 2016-07-15 06:04
@rodrigopr Does your app also redefine all the containers in every http request (by calling `createContainer`)? The face that the cache size is being exceeded is an indication that the application is doing unnecessary recomputation on each request; you could probably get a general performance boost by defining components/containers just once (they're meant to be reusable). 

We would consider adding some way to reset these caches, but I suspect that doing so in this case would mask a larger performance problem in your app.

**Comment by rodrigopr** [comment] 2016-07-15 06:50
I'm afraid react-router-relay and isomorphic-relay creates an QueryAggregator (similar to a RelayContainer) per render (see [react-router-relay/blob/master/src/QueryAggregator.js](https://github.com/relay-tools/react-router-relay/blob/master/src/QueryAggregator.js#L186-L207) and [isomorphic-relay-router/src/prepareData.js](https://github.com/denvned/isomorphic-relay-router/blob/master/src/prepareData.js#L6-L12))

**Comment by josephsavona** [comment] 2016-07-15 16:48
@rodrigopr Hmm. Those packages may be somehow redefining containers, but there isn't anything immediately obvious in the sections you linked to. I would recommend adding a breakpoint in `buildRQL` or `getRelayQueries` for cache misses to see what's causing the memory to grow so much (maybe [here](https://github.com/facebook/relay/blob/master/src/container/getRelayQueries.js#L42)).

**Comment by rodrigopr** [comment] 2016-07-15 17:03
@josephsavona thanks for the quick feedback.

I'll debug it further on that line, but if I understood correctly the `Component` on the line you pointed is an instance of `QueryAggregator`, which are created once per request (on `isomorphic-relay-router/src/prepareData.js` I mentioned).

I'll also investigate how can we to avoid creating a QueryAggregator instance per server-side render, but probably will require a large change in react-router-relay.

**Comment by tomconroy** [comment] 2016-07-19 16:06
We ran into this problem after putting a server-rendering relay app into production. Our app would crash every few hours. I forked relay to disable these queryCache and componentCaches and it appears to fix our problem.

https://github.com/tomconroy/relay/commit/c71e00bc84feb31b68f8714ab049a1e96fcc55b9

Deployed at 10am, the memory appears to have stabilized:

<img width="2378" alt="nib-memory" src="https://cloud.githubusercontent.com/assets/1223187/16957084/fe106f9e-4da8-11e6-9dd8-5ca989dd0bef.png">

**Comment by josephsavona** [comment] 2016-07-19 19:36
Thanks for the feedback. Ideally we'd address the root cause - not repeatedly creating things that look like containers but aren't - but we're open to a PR that addresses this in Relay for now.

This could be a global, public function `Relay.disableQueryCache()` that sets a module-scoped flag in `getRelayQueries` and `buildRQL` to disable caching (where the flag would default to true). Note that the `typeof window === undefined` isn't a reliable check for the server, as window can also be undefined in other client environments (such as React Native). We're open to PRs along the lines of this `disableQueryCache()` function.

**Comment by nthtran** [comment] 2016-07-22 08:01
@tomconroy Are you using `isomorphic-relay-router`? `isomorphic-relay-router` creates a [new `QueryAggregator` for every request](https://github.com/denvned/isomorphic-relay-router/blob/master/src/prepareData.js#L6). Which is later passed to `RelayReadyStateRenderer` where `getRelayQueries` is [called for every `render()`](https://github.com/facebook/relay/blob/master/src/container/RelayReadyStateRenderer.js#L100).

Ideally there should be a way `isomorphic-relay-router` should cache `QueryAggregator` for every possible route combination.

**Comment by tomconroy** [comment] 2016-07-22 12:53
Indeed, moving this over to https://github.com/denvned/isomorphic-relay-router/issues/40

**Comment by josephsavona** [comment] 2016-07-22 15:51
> Ideally there should be a way for isomorphic-relay-router to cache QueryAggregator for every possible route combination.

Yes! This seems like the ideal solution to this issue.

**Comment by KCraw** [comment] 2016-07-24 23:56
@josephsavona I've been playing with this and I'm going to comment over on denvned/isomorphic-relay-router#40, but can you confirm for me that `getRelayQueries` is expecting a class/constructor and not an instance of a component?

**Comment by josephsavona** [comment] 2016-07-25 02:12
Yup, it expects a class.

**Comment by KCraw** [comment] 2016-07-25 06:46
@josephsavona Thanks! Any chance of letting it accept either; i.e., check if Component is a function, and if not, use Component.constructor as the key?

The reason I ask is I don't think caching any sort of query config aggregator is going to work for SSR. Otherwise you're bound to have concurrency problems. And any sort of query config aggregator is likely going to have to fake the `RelayContainer` static methods with instance methods, since by definition the fragments on a query aggregator rely on the children it is wrapping. Nor do the `RelayContainer` static methods provide any sort of argument that might allow for a query config aggregator to identify an instance in an internal registry. And turning off caching to avoid the issue is undesirable. Maybe there is some implementation of a query config aggregator that avoids these problems, but if so, it eludes me. 

I'd be a little concerned with an 'accept an instance or a class' solution that there are other internal portions of Relay that rely on the Relay.Renderer Container prop being a class and not an instance. On the other hand, routing and nested routes seems pretty important, and having lots of nested Relay.Renderers sounds bad to me (but maybe I'm wrong on that). So a query aggregator is pretty much a given.

**Comment by josephsavona** [comment] 2016-07-25 15:53
> Any chance of letting it accept either; i.e., check if Component is a function, and if not, use Component.constructor as the key?

I don't think this solves the problem, since the constructor would presumably be shared amongst all `QueryAggregator` instances. This would mean that all aggregators would use the fragments of whatever aggregator happened to have been seen first -  not good.

I believe that the issue is that a new QueryAggregator is created for each new request. Instead, it should be possible to create one aggregator per unique route combination. Fo example if `/foo` can have two child routes `/foo/bar` and `/admin/baz`, then each of the latter would have a cached aggregator. It isn't clear why a new aggregator would need to be recreated when re-encountering a previously seen route, as only the params on the Route object change.

I'd really recommend submitting a PR to allow manually disabling the cache. If you are using `isomorphic-relay` you are not getting the benefits of the component/route cache anyway, so we might as well disable it to at least avoid the memory problem. Note that this cache is originally optimized for Relay running on low-end mobile devices: having the cache is not critical on the server.

**Comment by KCraw** [comment] 2016-07-25 20:24
Sorry to drag this convo out here, but I think it's relevant to anyone dealing with query aggregation and how to properly implement it with Relay, and not just iso-relay, react-relay-router, etc. 

> I don't think this solves the problem, since the constructor would presumably be shared amongst all QueryAggregator instances. This would mean that all aggregators would use the fragments of whatever aggregator happened to have been seen first - not good.

This brings up a concern with aggregation generally. `QueryAggregator` (as implemented in react-router-relay) appears to be generating responses to requests for fragments and queries dynamically, so when `getRelayQueries` is building its cache, we end up with with a single Component key in the `queryCache` which maps to a cache object with (eventually) a key for every possible route combination; e.g., something like this on the client (generated without SSR):

<img width="1371" alt="screen shot 2016-07-25 at 1 36 30 pm" src="https://cloud.githubusercontent.com/assets/8075821/17112720/dec998a4-526c-11e6-9494-6de91204193b.png">

From your perspective, is this problematic with how Relay does things internally?

> It isn't clear why a new aggregator would need to be recreated when re-encountering a previously seen route, as only the params on the Route object change.

My concern is whether anything async is happening between the time one request initiates use of the `QueryAggregator` and when it is released following the SSR. If so, another req for the same path from another user could modify the `QueryAggregator` while it is in use. If Relay doesn't do anything async until the actual GraphQL request, we could use one `QueryAggregator` cache for preparing data and another for the actual SSR, but you'd still have to guarantee nothing async would ever happen between checking out the `QueryAggregator` and the GraphQL request , and that's a problem if you use promises anywhere. You'd need to keep some sort of pool of QueryAggregators, you could even do it per unique route, but that would only slow down the memory leak.

Or as you suggest, just enable turning off the cache on the server. Definitely the simplest and solution. Perfectly happy to work on it and submit a PR.

However, based on your reply, I'd like to verify that there isn't a problem with how `QueryAggregator` interacts with the query cache on the client, where we can't just turn the cache off to get around the issue. If so, then a completely different solution for query aggregation might be needed.

**Comment by denvned** [comment] 2016-07-26 05:28
> It isn't clear why a new aggregator would need to be recreated when re-encountering a previously seen route, as only the params on the Route object change.

@josephsavona The problem was that *react-router-relay*, on which *isomorphic-relay-router* is based, is designed in such a way that there supposed to be an unique instance of `QueryAggregator` per each `Router` instance, and trying to reuse a `QueryAggregator` concurrently would lead to problems even when the route is absolutely the same.

But I believe I finally managed to solve the issue by refactoring the container responsibility of `QueryAggregator` out to a new class `AggregateContainer`, and reusing instances of this class instead. See https://github.com/denvned/isomorphic-relay-router/commit/9a98a195f7d1287975958528ddf54275e28757d2

**Comment by KCraw** [comment] 2016-07-26 15:34
I think @denvned's solution fixes the issue with routing and query aggregation, and in a quick test, the cache seems to building as intended by Relay on both the client and server.

That being said, I think we're still going to need to a way to manually disable Relay's caches on the server as @josephsavona suggested. This is completely independent of routing. 

Relay caches use the params in generating cache keys as well, which would quickly grow out of hand on the server (as @josephsavona stated, the cache was never intended for server use). Just imagine how many cache keys would be generated for a Component if something like a text search string were a param, or even just the ids of nodes for large applications.

**Comment by KCraw** [comment] 2016-07-26 20:59
Submitted a very simple PR that addresses the above issue and allows for disabling the query caches with `Relay.disableQueryCache()`

https://github.com/facebook/relay/pull/1302

**Comment by denvned** [comment] 2016-07-27 04:46
> Relay caches use the params in generating cache keys as well, which would quickly grow out of hand on the server

Or alternatively to disabling cache altogether this can be solved by incorporating LRU cache. This way we would not introduce new public API, also cache still might provide some performance benefit on the server.

**Comment by KCraw** [comment] 2016-07-27 06:12
I think an LRU would be a far more elegant solution for sure. It would also fix the issue client side--even though the likelihood of encountering the problem during normal usage is low, it still bothers me that it's possible. 

An LRU implemented with WeakMap might also be a solution for QueryAggregator, since single-use instance objects and their cache entries could be garbage collected once SSR was finished with them, while classes or instances strongly referenced elsewhere would remain. However, I'm not sure if WeakMap is supported by all the browsers Relay is targeting.

**Comment by fabiosantoscode** [comment] 2016-07-27 08:34
Unless this serverside LRU cache can be turned off, I can personally say it is still an issue for me. Serverside users of Relay may not always want an in-process cache. In fact, it can be harmful to reactive architectures in situations where constructing a fresh version of the HTML is crucial.

**Comment by denvned** [comment] 2016-07-27 09:14
> In fact, it can be harmful to reactive architectures in situations where constructing a fresh version of the HTML is crucial.

@fabiosantoscode I don't quite understand what you mean. I think a combination of a container and a query configuration, which is used as the cache key, always yields the same set of relay queries, thus should be safe for caching (in case when the cache doesn't grow unboundedly).

**Comment by fabiosantoscode** [comment] 2016-07-27 19:36
> @fabiosantoscode I don't quite understand what you mean. I think a combination of a container and a query configuration, which is used as the cache key, always yields the same set of relay queries, thus should be safe for caching (in case when the cache doesn't grow unboundedly).

Thanks for the clarification, I seemed to have misread and thought an in-process cache for query _responses_ was being considered. I will keep quiet now :)

**Comment by KCraw** [comment] 2016-08-04 18:51
@josephsavona  Any thoughts on using LRU cache for these two caches? Would you be open to a PR that implemented something like a `RelayLRUCache` module that would abstract all this away, and would allow globally setting the cache size (using `0` to turn them off and setting the default as `Infinity`)?

If so, I'm willing to take a stab at it in the nearish future (I'd have to make time), or maybe @denvned would be willing (he's cleverer than I am anyways).

**Comment by fabiosantoscode** [comment] 2016-09-03 13:26
After an update to 0.9.3, which contains the above commit, it seems like our memory leak is completely gone. Further investigation will occur on my side, but my guess is that this issue can be closed.

**Comment by josephsavona** [comment] 2016-09-03 18:49
@fabiomcosta Thanks for confirming. I'm going to close as the use of this feature completely disables the caching that caused the bug - feel free to file a new issue if there are any remaining problems!

**Closed by josephsavona** 2016-09-03 18:49 UTC

**Comment by taion** [comment] 2016-11-03 16:35
I think the query cache should be an LRU, or otherwise customizable (perhaps with continuation local context to be request-scoped).

Without some sort of caching, it's impossible to avoid doing extra work – the queries need to be built to fetch data, but then `Relay.ReadyStateRenderer` also needs to build the queries to actually do the render.

**Comment by taion** [comment] 2016-11-03 16:37
Or – would it be possible to move `getQueries` to the Relay environment? At least in the OSS Relay code base (and in all of my own code), I don't call `getQueries` without access to an actual Relay environment. The top-level static implementation could just use `Relay.Store`.
