### ISSUE TITLE
GraphQL end of line issue on OSX

### ISSUE THREAD

**Issue by OmgImAlexis** [facebook/relay#77] opened 2015-08-15 05:36 UTC
In the todo example I'm getting this from the Graph page.
````
{
  "errors": [
    {
      "message": "Syntax Error GraphQL request (1:1) Unexpected EOF\n\n1: \n   ^\n",
      "locations": [
        {
          "line": 1,
          "column": 1
        }
      ]
    }
  ]
}
````

**Comment by josephsavona** [comment] 2015-08-15 20:37
Hi, can you provide steps to reproduce this issue? Also, are you on latest (master)?

**Comment by fson** [comment] 2015-08-15 20:39
@OmgImAlexis This looks like the error you get from the GraphQL server if you did not pass a query or the query you passed was empty. Can you check that you are accessing the app on [http://localhost:3000](http://localhost:3000)? The example server listens in two ports, the app on port `3000` and the GraphQL server on port 8080.

If you want to try the GraphQL server without using the app, you can do so with curl, for example:
```
curl -X POST http://localhost:8080/graphql \
  -H "Content-Type: application/graphql" \
  -d '{ viewer { todos { totalCount } } }'
```
Or with JSON:
```
curl -X POST http://localhost:8080/graphql \
  -H "Content-Type: application/json" \
  -d '{"query": "{ viewer { todos { totalCount } } }"}'
```

**Comment by OmgImAlexis** [comment] 2015-08-15 22:52
@fson You're right, I haven't played with GraphQL before so I wasn't sure what to expect from that. Saying so, that sounds like a weird error to throw back when an empty query is passed to it, don't you think?

**Comment by fson** [comment] 2015-08-17 21:02
@OmgImAlexis The error message has been improved in the newer version of `express-graphql`, which now returns this error message:
```json
{
  "errors": [
    {
      "message": "Must provide query string."
    }
  ]
}
```

I've opened a pull request (#93) to update the version of this package used in the examples.

**Comment by yungsters** [comment] 2015-08-18 08:23
Closing this out in favor of #93.

**Closed by yungsters** 2015-08-18 08:23 UTC
