### ISSUE TITLE
Pagination impossible?

### ISSUE THREAD

**Issue by BerndWessels** [facebook/relay#743] opened 2016-01-14 02:17 UTC
I try to get a connection with pagination working.

![pagination](https://cloud.githubusercontent.com/assets/1776695/12314132/1174bc02-bad3-11e5-8eef-1852a9cae9c8.png)

But it looks like that there is nothing in Relay that supports the basic pagination features like:
* total pages
* current page
* go to specific page

Unfortunately `first after` and `last before` are not good enough to implement proper pagination.

I even tried to extend the connection like this:

    var {connectionType: postsConnection} = connectionDefinitions({
      name: 'post',
      nodeType: qlPost,
      connectionFields: () => ({
        totalCount: {
          type: GraphQLInt,
          resolve: (connection) => connection.totalCount,
          description: `A count of the total number of objects in this connection, ignoring pagination.`
        },
        currentPage: {
          type: GraphQLInt,
          resolve: (connection) => connection.currentPage,
          description: `The current page index in this connection.`
        },
        totalPages: {
          type: GraphQLInt,
          resolve: (connection) => connection.totalPages,
          description: `A count of the total number of pages in this connection.`
        }
      })
    });

But even this is a dead end since `currentPage` is not updated with subsequent calls.

Is there anything in Relay to create proper pagination?

If not, can you guys implement a new connection that can do proper pagination?

**Comment by josephsavona** [comment] 2016-01-14 04:14
Closing as this is a duplicate of #540 - feel free to ask questions or comment there.

**Closed by josephsavona** 2016-01-14 04:14 UTC

**Comment by josephsavona** [comment] 2016-01-14 04:21
Note that @taion has suggested a very simple way to achieve this type of pagination - see his comments and the discussion at https://github.com/facebook/relay/issues/540#issuecomment-155531357
