### ISSUE TITLE
isScalarAndEqual returns true on functions

### ISSUE THREAD

**Issue by taion** [facebook/relay#1404] opened 2016-10-03 23:20 UTC
Currently, `isScalarAndEqual` only treats values that have type `object` as non-scalar: https://github.com/facebook/relay/blob/v0.9.3/src/container/RelayContainerComparators.js#L55

Notably, this check doesn't cover functions. While this isn't causing actual problems for us, it's a bit surprising – given the name of `isScalarAndEqual`, it's surprising that it treats functions as "scalar".

cc @itajaja

**Comment by wincent** [comment] 2017-01-31 00:26
Thanks for bringing this up @taion.

My reading of this is that the behavior is as intended, so we shouldn't change that, but the naming has caused confusion, which suggests that there might be a better name for this.

The intent here is that we should consider the props equal if they are identical (`===`) and have the same contents. Because values which are "containers" (things like objects, and arrays, for which `typeof` is going to be `'object'`) can retain their identity (`===`) but actually have their contents changed, we want to exclude those from the check. Functions, on the other hand, are seldom treated as "containers" (even though, sure, you can mutate them by changing their properties), so we want to allow the common case (people passing callback functions as props) to not trigger any unnecessary operations, provided the same functions (`===`) continue to be passed in.

So, I'm going to close this in the interests of keeping the issue tracker clean, but if you can come up with a better name for `isScalarAndEqual` that doesn't lead to confusion, please do submit a PR and we'd be happy to look at it. Naming is hard, so in thinking about this for a few seconds, all that comes to my mind is `isNonObjectAndEqual` or `isEqualAndNonObject`. Even those have some conceptual muddiness, because there is a number of JS types that return `'object'` for `typeof`, but it may still be an improvement. I guess if all else fails and we can't solve this with a better name, we could add a comment above the function as a last resort.

Thanks once again for your contribution!

**Closed by wincent** 2017-01-31 00:26 UTC
