### ISSUE TITLE
Error Running Example TodoMVC React Native

### ISSUE THREAD

**Issue by CoericK** [facebook/relay#1222] opened 2016-06-19 05:40 UTC
1. Git clone the current version of the repo
2. cd /relay/examples/TodoMVC
3. npm install (everything installs ok)
4. npm start
5. Get this ugly log

```
Ericks-iMac:TodoMVC erick$ npm start

> TodoMVC@0.0.1 start /XXX/react-native/relay/examples/TodoMVC
> babel-node ./server.js

/XXX/react-native/relay/examples/TodoMVC/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (/XXX/react-native/relay/examples/TodoMVC/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:126:28)
    at OptionManager.addConfig (/XXX/react-native/relay/examples/TodoMVC/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:107:10)
    at OptionManager.findConfigs (/XXX/react-native/relay/examples/TodoMVC/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:168:35)
    at OptionManager.init (/XXX/react-native/relay/examples/TodoMVC/node_modules/babel/node_modules/babel-core/lib/transformation/file/options/option-manager.js:229:12)
    at compile (/XXX/react-native/relay/examples/TodoMVC/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:117:22)
    at normalLoader (/XXX/react-native/relay/examples/TodoMVC/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (/XXX/react-native/relay/examples/TodoMVC/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)


```

**Comment by wincent** [comment] 2016-06-22 02:40
Thanks for the report, @CoericK, but this is a dupe of #1188. I'm going to close this one. Please see the other issue for [workaround](https://github.com/facebook/relay/issues/1188#issuecomment-227535665) and imminent fix.

**Closed by wincent** 2016-06-22 02:40 UTC
