### ISSUE TITLE
RANGE_ADD issues with custom params in a connection

### ISSUE THREAD

**Issue by johanobergman** [facebook/relay#604] opened 2015-11-16 17:08 UTC
I have a `Calendar` component with a query that looks like this:
```graphql
items(first: 99999, startDate: $start, endDate: $end) { edges { node {
    ...
}}}
```
It is possible to navigate between time periods (like months), and this is done with a `react-router` link together with `react-router-relay`. So far, everything works fine.

When I run a mutation to add an item using `RANGE_ADD`, it does fire off the correct network request, but no item is added to the cache. After this has happened, navigating to previously loaded calendar views breaks because `relay` serves the calendar the cache which was currently in use when the `RANGE_ADD` mutation happened, even though the connection params are different.

I was able to make the mutation work correctly by specifying my `rangeBehaviors` in two ways, one with `startDate` first and one with `endDate` first. This is obviously not the way to go and even throws an error in `relay 0.5`, and the cache still breaks (although not as consistently).

I am generating my `rangeBehaviors` on the fly by looping over a list of all visited start- and endDates. I don't know if that's the issue, but I see no other way of specifying correct `rangeBehaviors`.

**Comment by taion** [comment] 2015-11-17 14:25
I think this is effectively just https://github.com/facebook/relay/issues/542.

Make sure you also have an unterminated query for the connection field, like in the TodoMVC example.

**Comment by yuzhi** [comment] 2015-11-17 16:21
What does the `getConfig` of your mutation look like? Can you also include the server response?

**Comment by yuzhi** [comment] 2015-11-17 22:20
Sounds like you were able to get the edges to be added by having `startDate` and `endDate` in alphabetical order. 
We should have fixed the alphabetical order issue already. What version of Relay are you using? What error is it throwing in `Relay 0.5`?

Also, what can you clarify you mean by the cache still breaks? Is it still showing old data? Could it be something `react-router-relay` is caching by accident? We should be fetching data from Relay cach

**Comment by johanobergman** [comment] 2015-11-17 22:36
I'm using `relay 0.5`. I don't get any error at all if my `rangeBehaviors` are in alphabetical order. However, i also have to specify the parameters in my *query* in alphabetical order in order for the item to actually appear in my views.

Regarding the cache problem - let's say I refresh the page, and click through a few months so that there are a couple of cached queries. I then add a new item with the mutation above, and it shows up. This is where the cache breaks. When I navigate back to the previous views, they all receive the same items - namely the ones that were fetched from the __first__ displayed month (at page load).

I have checked the query params that `react-router-relay` feeds into the container, and they are correct for every month. The container just won't retrieve the correct items.

**Comment by yuzhi** [comment] 2015-11-17 23:13
Thanks! That's really useful.
1. It sounds like there is a bug, since the query shouldn't need to be in alphabetical order. I think @steveluscher will be the best person to look into that.

2. I am not familiar with `react-router-relay` and what side effect it might have. Just to be sure, can you check the query variables inside the container with the query of the connection where it includes dates as the variables? Do you know whats the top-level code Relay it calls with when `back` is clicked? Does it make a new RelayRootContainer? Does it remember the results of all the `setVariables` calls that were used?

**Comment by taion** [comment] 2015-11-17 23:15
Currently we use a single `RootContainer` that aggregates all the queries together, then distribute the results of those queries back to each route container.

@johanobergman Are you doing anything w/e.g. `prepareParams`? There is an open issue there w/https://github.com/relay-tools/react-router-relay/issues/79.

**Comment by johanobergman** [comment] 2015-11-17 23:23
> Just to be sure, can you check the query variables inside the container with the query of the connection where it includes dates as the variables?

The variables are correct as far as I can see (I console.log'd them in `prepareVariables`). Also, when I mean navigate back it doesn't have to be using the back button. Simply pressing a navigation arrow in my calendar ui does the same thing.

@taion I am using `prepareVariables` on the relay container to compute the relay variables `startDate` and `endDate` from the url query params `date` and `mode`. Not using `prepareParams` though.

**Comment by steveluscher** [comment] 2015-11-19 01:44
We're missing a `.sort()` [here](https://github.com/facebook/relay/blob/master/src/traversal/writeRelayUpdatePayload.js#L561). My bad. Fix coming.

**Comment by johanobergman** [comment] 2015-11-19 10:59
@steveluscher Great!

I'm still not sure if the cache issue is caused by `relay` or `react-router-relay`. I changed my implementation to use `relay.setVariables` instead of query params with `react-router-relay`, but the result was still the same.

**Comment by yuzhi** [comment] 2015-11-19 18:27
Awesome! We found the root cause of the one of the problems. Let's keep digging into the other one.
So the mutation went through and updated one of the connection, but either it didn't update the other connections or they were not read out again properly. 
When you do `this.props.relay.setVariables`, do you still get the very first page that was rendered or does it just not show the new item that should have been added?
Is it possible for you to add a `console.log` around here: https://github.com/facebook/relay/blob/master/src/traversal/writeRelayUpdatePayload.js#L426  and see if it is getting called for each of the cached connections?

**Comment by johanobergman** [comment] 2015-11-19 20:02
After I ordered the parameters in my queries (while waiting for the fix), my mutation is now 100% successful, and the item is always added to `viewer.items` and consequently to the view.

`writeRelayUpdatePayload.js#L426` is only called once, and it should be - my item does only belong in one or possibly two connections at the same time (the "month" and the "four weeks" view).

The issue is that after I do `relay.setVariables` with parameters for already cached connections, *no matter if they should contain the newly added item or not*, `viewer.items` returns the wrong set of data. Earlier today it was always the first loaded query data, but right now it appears to be the data from the second cached query (makes no sense).

**Comment by yuzhi** [comment] 2015-11-19 22:05
That sounds super weird.  @taion could react-router-relay be doing any weird caching?
@johanobergman do you think you can make minimal repro case for the `setVariables` problem?

**Comment by taion** [comment] 2015-11-19 22:11
I don't explicitly do any caching.

@johanobergman When you drop RRR, are you still using `prepareVariables`? If so, can you see what happens if you drop `prepareVariables`?

**Comment by johanobergman** [comment] 2015-11-19 22:28
@taion It made no difference, sadly. When you say drop - `react-router-relay` is still around, I've just replaced my `<Link>`s with `relay.setVariables`.

**Comment by taion** [comment] 2015-11-19 22:32
Can you try dropping `prepareParams`?

**Comment by johanobergman** [comment] 2015-11-19 22:35
I haven't defined `prepareParams`. I dropped `prepareVariables` and made the computations (transforming a single date into `startDate` and `endDate`) before the call to `relay.setVariables`.

**Comment by johanobergman** [comment] 2015-11-19 23:01
@yuzhi I made some digging starting from `RelayContainer@componentWillReceiveProps`. In `_getQueryData()`, the `fragmentPointer` appears to be correct, and `queryResolver.resolve(fragmentPointer)` returns an object where the `__dataID__` property corresponds to the connection I want to load, but the `edges` property contain the wrong edges.

Is it possible to set a breakpoint somewhere to see all cached connections keyed by `__dataID__`? I'm curious if my mutation overwrites all caches with the first (or second or whatever) cache.

**Comment by taion** [comment] 2015-11-19 23:33
Oops, sorry, I meant `prepareVariables`.

I'm really not sure - I've seen some weird things happen when I used `setVariables`, but I never got around to setting up a consistent repro, and just cargo culted stuff around until it worked.

**Comment by johanobergman** [comment] 2015-11-19 23:43
I'm going to try to whip something up tomorrow if I have time for it.

**Comment by johanobergman** [comment] 2015-11-22 14:45
A quick question - do I have to specify all queried connections with their respective params in `rangeBehaviors`? In other words, is there a difference between specifying `rangeBehaviors['endDate(xxxx).startDate(xxxx)'] = ''` and omitting that `rangeBehavior`?

I've made a test repo based of `relay-starter-kit`, and `relay` seems to do a full query on `viewer { items }` unless I specify all possible `rangeBehaviors`. #615 would simplify this a lot.

**Comment by johanobergman** [comment] 2015-11-22 17:32
So, I haven't been able to 100% reproduce the issue. In my test repo, `relay` re-fetched all of the previously visited connections, since I only specified `rangeBehaviors` for where the item should be added. In my real app however, it didn't even do that, instead the cache broke.

I was able to work around it by caching the arguments for every single visited connection and set all of their `rangeBehaviors` to an empty string (except the `append` one).

I made something that resembles what's proposed in #615 to simplify this a bit: https://gist.github.com/johanobergman/8f829faa0eb76cdc22a8

**Comment by taion** [comment] 2015-11-22 18:19
https://github.com/facebook/relay/issues/604#issuecomment-158764421: I believe specifying `''` or `null` means "nothing changes" - I use it for e.g. https://github.com/facebook/relay/blob/master/examples/todo/js/mutations/AddTodoMutation.js#L49

**Comment by josephsavona** [comment] 2015-11-29 19:09
> I made something that resembles what's proposed in #615 to simplify this a bit:

@johanobergman Nice! It sounds like this gives you a workaround for now, and #615 will make it easier to do this. I'll close this for now, but feel free to continue discussion and we can reopen if necessary.

**Closed by josephsavona** 2015-11-29 19:09 UTC
