### ISSUE TITLE
relay-compiler Expected undefined to be a GraphQL leaf type.

### ISSUE THREAD

**Issue by graingert** [facebook/relay#2285] opened 2018-01-17 13:42 UTC
relay-compiler assumes ID type is available.

https://github.com/facebook/relay/issues/1880#issuecomment-307705428

**Comment by sibelius** [comment] 2018-01-17 13:48
fixed here https://github.com/facebook/relay/pull/2249

**Comment by alloy** [comment] 2018-01-29 10:38
Duplicate of #2281 for which PR #2290 exists, although if #2249 indeed fixes this case then it might make sense to go that route instead of slightly patching the symptom.

@jstejada In the meantime, this one can be closed in favour of the other ticket/PR.

**Comment by jstejada** [comment] 2018-02-04 22:08
thanks @alloy, closing in favor of #2281

**Closed by jstejada** 2018-02-04 22:08 UTC
