### ISSUE TITLE
refetchVariables of RefetchingContainer.refetch is called with default fragment variables instead of previous variables

### ISSUE THREAD

**Issue by mmjd** [facebook/relay#1986] opened 2017-07-23 07:05 UTC
```javascript
 _loadMore() {
    // Increments the number of stories being rendered by 10.
    const refetchVariables = fragmentVariables => ({
      count: fragmentVariables.count + 10,
    });
    this.props.relay.refetch(refetchVariables, null);
  }
}

module.exports = createRefetchContainer(
  FeedStories,
  {
    feed: graphql.experimental`
      fragment FeedStories_feed on Feed 
      @argumentDefinitions(
        count: {type: "Int", defaultValue: 10}
      ) {
        stories(first: $count) {
          edges {
            node {
              id
              ...Story_story
            }
          }
        }
      }
    `
  },
  graphql.experimental`
    query FeedStoriesRefetchQuery($count: Int) {
      feed {
        ...FeedStories_feed @arguments(count: $count)
      }
    }
  `,
```

fragmentVariables is always {count: 10, after: undefined}

**Comment by sibelius** [comment] 2017-07-23 18:43
is this happening in this version https://github.com/facebook/relay/releases/tag/v1.2.0-rc.1?

**Comment by mmjd** [comment] 2017-07-24 04:37
yes I tested it with 1.2.0-rc.1 and the result is the same

**Comment by sibelius** [comment] 2017-07-24 10:39
@Yan-J I can confirm this behavior

**Comment by sgwilym** [comment] 2017-07-24 11:15
This might be a duplicate of #1984, which I also experienced outside of compat mode.

**Comment by sibelius** [comment] 2017-09-25 16:27
@mmjd is this still happening?

**Comment by bochen2014** [comment] 2017-10-23 12:11
I can confirm that [my pr](https://github.com/facebook/relay/pull/1868) can solve this problem

**Comment by bochen2014** [comment] 2017-10-24 11:34
```JSON
    "react-relay-pr-1868": "^1.4.1",
    "relay-compiler-pr-1868": "^1.4.1",
    "relay-runtime-pr-1868": "^1.4.1",
```
in `webpack.config.js`, add
```javascript
  resolve: {
    alias: {
      "react-relay": "react-relay-pr-1868",
      "relay-runtime": "relay-runtime-pr-1868",
    }
  },
```

then do the normal stuff. now `relay.refetch` should always use the latest variables

**Comment by tomas-paronai** [comment] 2017-11-20 11:28
Ok It looks like with module version 1.4.1 the refetch container did updated my comp with expected data.

**Comment by tomas-paronai** [comment] 2017-11-29 08:38
UPDATE: Ok it doesn't work again I don't understand why. My observation:
I have put logs inside:
1. fetch function
2. QueryRenderer render function
3. RefetchContainer render function

When I run the component first time, I get logs from all 3 with expected data.
When I do the refresh, I get logs only from the fetch and RefetchContainer render. BUT, the data inside the fetch is as expected but the data inside the render are the old one. 

When I wrote the comment above that it is working it was! I am not sure what did I mistype or misspell during the implementation.

QueryRenderer query looks like this:
```
query Home_Query {
                        section: field (ref: "...somePath...") {
                            ...SectionFragment_section
                        }
                    }
```

RefetchContainer query:
```
{
        section: graphql'
            fragment SectionFragment_section on Content  @argumentDefinitions (
                size: {type: "Int", defaultValue: 5 }
            ) {
                ...
            }
        '
    },
    graphql'
        query SectionFragmentQuery($path: String!, $size: Int!){
            section: field(ref: $path) {
                ...SectionFragment_section @arguments(size: $size)
            }
        }
    '
```

and if it helps my refresh function:
```
refresh() {
        const refetchVariables = () => ({
            path: this.props.path,
            size: 5
        });
        this.props.relay.refetch(refetchVariables, null);
    }
```

**Comment by jstejada** [comment] 2018-08-27 04:08
This has been fixed!

**Closed by jstejada** 2018-08-27 04:08 UTC
