### ISSUE TITLE
[modern rc3] RelayModernFragmentSpecResolver refetch sees no difference

### ISSUE THREAD

**Issue by decebal** [facebook/relay#1759] opened 2017-05-15 14:59 UTC
Although the network request is successful the props are not mapped right, hence the component never gets updated!

Flow: `createRefetchContainer()` -> call `relay->refetch()`

**Comment by chollier** [comment] 2017-05-15 15:42
Most likely a duplicate of https://github.com/facebook/relay/pull/1702

**Comment by yuzhi** [comment] 2017-09-11 17:52
@chollier Sounds like it was a dup of  #1702 has been resolved. Please open a new issue if it's still broken for you.

**Closed by yuzhi** 2017-09-11 17:52 UTC
