### ISSUE TITLE
Throw an error(warning) when pass null to relayContainer with other props

### ISSUE THREAD

**Issue by yodairish** [facebook/relay#753] opened 2016-01-19 21:35 UTC
If I send to the relay component null as a fragment and this component also has other props with indexes(like string or array) then it can throw an error if fragment has instanceHash same as index in value one of these props
```
var Test = props => <span>{`${props.test ? props.test.hello : 'hello'} ${props.world}`}</span>;

Test = Relay.createContainer(Test, {
  fragments: {
    test: () => Relay.QL`
      fragment on Test {
        hello
      }
    `
  }
});

// ========
// if fragment will have a __concreteNode__.__instanceHash__ for example "3" it will throw
...
render() {
  return <Test world="some text" test={null} />
}
...
```

it's happened [here](https://github.com/facebook/relay/blob/master/src/container/RelayContainer.js#L586)

**Comment by wincent** [comment] 2016-02-04 23:35
Thanks for the report @yodairish. I am wondering, is this throwing an error, or just warning? If so, it may be a duplicate of #759, which is mitigated by 839eeb36814d (on `master`, but not in the current 0.6.1 release).

**Comment by wincent** [comment] 2016-02-08 22:13
Going to optimistically close this one for now. If this turns out to be in error, please comment and I'll re-open.

**Closed by wincent** 2016-02-08 22:13 UTC
