### ISSUE TITLE
this.props.relay.forceFetch() in parent container uses stale/default child variables

### ISSUE THREAD

**Issue by Globegitter** [facebook/relay#1138] opened 2016-05-13 14:20 UTC
In our app we have a structure as follows:

``` js
// ParentContainer.js which exports a RelayContainer with following query:
const RELAY_QUERY = {
  fragments: {
    something: () => Relay.QL`
      fragment on Something {
        ${InternalContainer.getFragment('treasury')},
        ...
      }
    `
  }
};

...

 class ParentContainer extends Component {

  onClick = (e) => {
    this.props.relay.forceFetch();
  };

  render() {
  ...
  return (
    ...
    <button onClick={this.onClick}>Press</button>
    <InternalContainer something={this.props.something}>
    ...
  )
  }
}

//InternalContainer.js which exports a RelayContainer with following query:
const FIRST_IN_LIST = '1';

const RELAY_QUERY = {
  initialVariables: {
    someArgument: FIRST_IN_LIST
  },
  fragments: {
    something: () => Relay.QL`
      fragment on Something {
        internals(someArgument: $someArgument) {
          id,
          transactions {
            amount
            description
            ...
          },
          ${InternalChildContainer.getFragment('account')}
        }
      }
    `
  }
};


class InternalAccounts extends Component {
  onShowInternalsClick = (selectedInternals) => {
    this.setState({fetchingTransactions: true}, () => {
      this.props.relay.forceFetch({someArgument: selectedInternals}, (readyState) => {
        if (readyState.done) {
          this.setState({fetchingTransactions: false});
        }
      });
    });
  };

  render() {
    ...
    <button onClick={this.onShowInternalsClick.apply(this, '1')}>Show first internals</button>
    <button onClick={this.onShowInternalsClick.apply(this, '2')}>Show second internals</button>
    // otherwise just renders the query data
  }
```

This example is a bit more contrived than our actual use-case but it should show our issue while keeping it simple and removing all sensitive data.

So we have two different `forceFetch` usages, one in the parent component and one in the child component. They are part of the same query but conceptually are responsible for two separate things: The parent is responsible for reloading the whole page and the child just for filtering out different data within itself (and its children).

The filtering in the child works fine, we can click the different buttons, the variable in the RelayContainer gets updated, etc. But now, when I press the button in the parent-component to reload the whole page the filter-variable in the child component is not being sent in its current state but as its default value. 

Our wanted behaviour is to send the variable of the child component in its current state. To me this seems like a bug as it in my opinion makes intuitive sense to send the current value rather than a stale/the default value of the child.

I also tried to track this down (via debugging when pressing the button in the parent) a bit but had to give up at https://github.com/facebook/relay/blob/master/src/query/buildRQL.js#L72. There I am seeing in the `fragmentCache` that there is an entry for the parent as well as the child fragment. The child has the correct up-to-date values, but the parent entry has the out-of-date values.

I will try to look a bit more into this, but it seems to me that the parent should just get the latest cached child fragment.

**Comment by josephsavona** [comment] 2016-05-13 16:04
Thanks for the detailed issue and example. This is a known behavior - let me first describe why, then next steps and workarounds.

Queries are constructed statically - the only inputs are the root variables (what you pass in `primeCache`/`forceFetch`/`setVariables`) and the *static* default variables for each fragment. Note that even where the *results* of a fragment will be a list, the query will contain only one fragment. For example the following query will (presumably) return multiple stories and render multiple `<Story>` components. But the query contains the `Story` fragment only once:

```graphql
fragment Feed on Viewer {
  stories(first: 10) {
    edges {
      ...Story
    }
  }
}
```

If two different `<Story>` components each set different variables, there's no good way for the static query to represent this (you'd have to construct a new query, creating a copy of every fragment that needed different variables, which isn't especially fast). 

`RelayContainer` partially addresses this scenario, however. If a child changes its variables, and then a parent changes its variables, the child will retain the changed variables *so long as the parent doesn't override the child's variables* (with `getFragment('...', vars)` + passing variables as props). We've found that this mitigates issues from different parent/child variables.. In other cases, it may be necessary to do something a bit more complicated, such as having the parent pass a callback to the child so that the parent can be responsible for the data-fetching.

All of that context out of the way, this is definitely something we'd like to find a better solution for. We've found this to be quite rare in practice, though, so we'd appreciate input from the community.

**Comment by Globegitter** [comment] 2016-05-15 16:53
> ...
If two different <Story> components each set different variables, there's no good way for the static query to represent this (you'd have to construct a new query, creating a copy of every fragment that needed different variables, which isn't especially fast).

Yeah that makes total sense. I mean for the unambiguous case (which ours is) it would of course be ideal if Relay would just refetch with the current set of variables rather than just blindly with the default variables.  But that of course is not a general solution and not sure how easy/hard it would be to implement, but imo worth thinking about.

Or for a more generic solution, how if we could specify something like: `this.props.relay.forceFetch(<ref to specific container>.getCurrentVariables())`. Or I guess more specific: 'For a specified fragment use the up-to-date variables from the specified container'. And probably it would then also be good to specify which variables you would like to take. I am not quite sure on the implementation of this, since you would need to keep references to containers, etc. But just an idea that would allow for this use-case, while still keeping the code clean and responsibility of functionality where it should be.

> RelayContainer partially addresses this scenario, however. If a child changes its variables, and then a parent changes its variables, the child will retain the changed variables so long as the parent doesn't override the child's variables (with getFragment('...', vars) + passing variables as props). We've found that this mitigates issues from different parent/child variables.

Can you go into a bit more detail of this scenario? It sounds very similar to the use-case I have given above, so not sure I fully understand? Or is that use-case different because the parent container has no variables itself?

>  In other cases, it may be necessary to do something a bit more complicated, such as having the parent pass a callback to the child so that the parent can be responsible for the data-fetching.

This was we are doing right now and it does feel like a hack that you always have to pull out all re-fetching logic to the highest level, of where you handle refetching. This could get unwieldy quite quickly for more complex uis. Are there currently no other workarounds for that? Ideally where we can keep control of refetching to the component that it should belong to (i.e. where the variables are specified).

In any case, thank you for giving some background on this, that makes the situation clearer.

**Comment by eyston** [comment] 2016-06-25 18:09
Howdy, just wondering if I get this ...

Given a `FeedComponent` with a `StoryComponent` child -- the fragment for both of these containers is static / global.  Any parent which references `StoryComponent` within itself is going to be referencing the same fragment (via the big fragment cache).  When any individual `StoryComponent` changes its variables these are reflected locally within the component instance -- when it constructs its own query for the context / store -- but if a parent re-evaluates its own query it will get the static fragment from cache.

Is this right?

Conceptually in my head I had thought that post-mounting the parent container got references to each of its child containers and would call `getFragment` on an instance vs class -- but that is never true, right?  It always goes to the class fragment (via the fragment cache)?  This makes a lot of sense for the example you bring up (it could be N children for a single fragment each with their own variable set).

I had just started looking over this part of the code (how containers work) last night and this issue was useful -- so thanks :)

**Comment by wincent** [comment] 2017-01-31 00:52
(Spring cleaning.) I'm going through and cleaning out issues that haven't had any activity for months. Thanks for participating in the discussion here. Given the imminent arrival of the new core and APIs (pieces of which have already landed on the `master` branch, with more to come over the coming weeks/months), I think it would be good to shelve this discussion for now, and wait for the arrival of the new core and APIs, which are built on a totally new refetching model (with explicit refetch queries), and once those are out in the open we can discuss any remaining issues. In the meantime, however, thanks very much for bringing this up in such detail.

**Closed by wincent** 2017-01-31 00:52 UTC
Labels: discussion

**Comment by bochen2014** [comment] 2017-03-06 06:05
@josephsavona  your reply makes perfect sense to me. I just ran into another scenario that is caused by the same nature. 
given
```
<Relay(Parent)>
          <Relay(Child) />
</Relay(Parent)>
```

if `Child` implements `componentDidMount` and does a `setVarialbes({some_var: newValue})` there, `Parent` won't be able to know what child's new variables are.
This will cause an issue that, if `Parent` later on decides to refresh itself (e.g. call `setState`), relay will re-render  `Relay(Child)` and gives a 
```
Warning: RelayContainer: component `ChildContainer` was rendered with variables that differ
from the variables used to fetch fragment `store`.
 The fragment was fetched with variables `{"some_var": null }` 
 but but rendered with variables `{"some_ar":"newValue"}`
```

the warning makes perfect sense to me --  `Parent` only knows about the `Child`'s static default variables, which `Child` has overridden in its `cdm`.  Due to
>If a child changes its variables, and then a parent changes its variables, the child will retain the changed variables so long as the parent doesn't override the child's variables (with getFragment('...', vars) + passing variables as props).

`Child` component's variables won't be overridden by `Parent` and can be resolved from `Relay Store` correctly, so everything works as expected. That said, the warning is a bit annoying, any idea how I can get rid of the warning without marking node_env as 'production'?

**Comment by bochen2014** [comment] 2017-03-17 03:48
a follow up on my last comment
>If a child changes its variables, and then a parent changes its variables, the child will retain the changed variables so long as the parent doesn't override the child's variables (with getFragment('...', vars) + passing variables as props).

I have
```
class Parent extends Compnent{
  refetch=()=>{
     this.props.relay.setVarialbes({  var1: 'var1'})
 }
   render(){
     const {variables: {var1, var2} } = this.props.relay
      return <div>
                         <Child  viewer={this.props.viewer} var1={ var1 } var2={var2} />
                         <button onClick={refetch}>parent-refetch</button>
               </div>
   }
}

export default Relay.createContainer(SearchContainer, {
    initialVariables: {
        var1: null,
        var2: null
    },
    fragments: {
        viewer: (variables) => Relay.QL`
            fragment on Viewer {
                ${child.getFragment('viewer', variables)} 
            }`
    }
})

-----------------

class Child extends Compnent{
  
  componentDidMount(){
       this.props.relay.setVarialbes({  var2: 'var2'})  // override the default var2 vlaue
  }

   render(){
     const { variables: {var1, var2} } = this.props.relay
      return <div>
          <span>{var1}</span>
          <span>{var1}</span>
   </div>
}

export default Relay.createContainer(SearchContainer, {
    initialVariables: {
        var1: null,
        var2: null
    },
    fragments: {
        viewer: (variables) => Relay.QL`
            fragment on Viewer {
                  stories(var1: $var1, var2: $var2){
                   id,
                   name,
                   comments
               }
            }`
    }
})
```

can someone tell me what is the expected `var1` and `var2` in the initial screen;
and what is the updated value after I click the `refetch` button?

**Comment by bochen2014** [comment] 2017-03-17 04:16
my relay version is shown below:
```
$ npm ls | grep react-relay
+-- @types/react-relay@0.9.10
+-- react-relay@0.9.3
```

**Comment by bochen2014** [comment] 2017-05-12 00:44
> If a child changes its variables, and then a parent changes its variables, the child will retain the changed variables so long as the parent doesn't override the child's variables (with getFragment('...', vars) + passing variables as props). `

i see what you mean now...  the overriding variables from `parent` doesn't necessarily contains all variables that `child` has. As along as `parent` passes something to `child`, all `child`'s previous variables are lost and overridden

how about we make a change to only reset `child` variables that `parent` has passed in?
