### ISSUE TITLE
Type generation for custom scallars

### ISSUE THREAD

**Issue by steida** [facebook/relay#2718] opened 2019-05-05 20:37 UTC
Something like this:

```ts
backingTypeMap: {
  EmailAddress: 'string',
  DateTime: 'string',
  Max1024Chars: 'string',
  Max140Chars: 'string',
  URL: 'string',
},
```

It would be awesome.

**Comment by TrySound** [comment] 2019-05-05 22:27
I currently solve this by copying RelayCompilerBin and RelayCopilerMain into the project and replacing empty `customScalars: {}` with this.
```js
        customScalars: {
          Date: 'String',
          DateTime: 'String',
        }
```

AFAIK guys discuss config file which should solve this problem.

**Comment by zth** [comment] 2019-05-06 07:24
I do the same thing, replace in the generated compiler bin and then check that into VCS. Not ideal, a config file would be very nice.

**Comment by sibelius** [comment] 2019-05-06 10:17
Right now you can use patch-package to make this easier

The right solution is a relay.config.js

**Comment by alloy** [comment] 2019-05-27 11:34
This seems a duplicate of #2162, for which there’s a PR at #2745.

**Closed by alloy** 2019-05-27 11:34 UTC
