### ISSUE TITLE
equality checking in recycleNodesInto.js

### ISSUE THREAD

**Issue by chungwong** [facebook/relay#2287] opened 2018-01-18 02:19 UTC
[These 3 lines ](https://github.com/facebook/relay/blob/master/packages/relay-runtime/util/recycleNodesInto.js#L52-L54) were added at https://github.com/facebook/relay/commit/efd18d6e6ff05449e48a05bc65e8874cdd6f80c3 to fix **read only property** warning.

Given that
`[1]  == [1]` evaluates `false`, this checking will fail on arrays which means the 3-line guard added will not work on arrays and will trigger
```
Uncaught TypeError: Cannot assign to read only property 'foo' of object '#<Object>'
```

**Comment by alloy** [comment] 2018-01-29 10:32
This is essentially a duplicate of #2049 and PR #2193 already exists to address it.

@jstejada This can be closed.

**Closed** 2018-01-29 23:58 UTC
