### ISSUE TITLE
Null value in list gets removed by Relay?

### ISSUE THREAD

**Issue by jardakotesovec** [facebook/relay#1252] opened 2016-07-01 11:43 UTC
When we send list of objects from server. 
```[{id: 'ab', name: 'foo'}, null, {id: 'cd', name:'bar'}]```

I am getting from relay container just 
```
[{id: 'ab', name: 'foo'}, {id: 'cd', name:'bar'}]
```
 
Null values gets removed. That seems to us as bug. Definitely not expected.  

Our use case is sending (similar to plural fields) array of some criteria and getting back array with results for each criteria and when its not found we return null.  

Here is [repro](https://facebook.github.io/relay/prototyping/playground.html#source=%2F**%0A%20*%20Copyright%20(c)%202013-present%2C%20Facebook%2C%20Inc.%0A%20*%20All%20rights%20reserved.%0A%20*%0A%20*%20This%20source%20code%20is%20licensed%20under%20the%20BSD-style%20license%20found%20in%20the%0A%20*%20LICENSE%20file%20in%20the%20root%20directory%20of%20this%20source%20tree.%20An%20additional%20grant%0A%20*%20of%20patent%20rights%20can%20be%20found%20in%20the%20PATENTS%20file%20in%20the%20same%20directory.%0A%20*%2F%0A%0A%2F%2F%20Welcome%20to%20Relay.%0A%2F%2F%20Allow%20us%20to%20introduce%20you%20to%20the%20four%20elements.%0A%0A%2F**%0A%20*%20%231%20-%20Your%20React%20components%0A%20*%20This%20will%20look%20familiar%20to%20React%20developers.%0A%20*%0A%20*%20To%20learn%20more%20about%20React%2C%20visit%3A%0A%20*%20%20https%3A%2F%2Ffacebook.github.io%2Freact%0A%20*%2F%0Aclass%20HelloApp%20extends%20React.Component%20%7B%0A%20%20render()%20%7B%0A%20%20%20%20%2F%2F%20Relay%20will%20materialize%20this%20prop%20based%20on%20the%0A%20%20%20%20%2F%2F%20result%20of%20the%20query%20in%20the%20next%20component.%0A%20%20%20%20%2F%2Fconst%20%7Bhello%7D%20%3D%20this.props.greetings%3B%0A%20%20%20%20console.log(this.props.greetings.hello)%0A%20%20%20%20return%20%3Ch1%3E%7B%7D%3C%2Fh1%3E%3B%0A%20%20%7D%0A%7D%0A%0A%2F**%0A%20*%20%232%20-%20Relay%20containers%0A%20*%20Compose%20your%20React%20components%20with%20a%20declaration%20of%0A%20*%20the%20GraphQL%20query%20fragments%20that%20fetch%20their%20data.%0A%20*%0A%20*%20To%20learn%20more%20about%20Relay%20containers%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fguides-containers.html%0A%20*%2F%0AHelloApp%20%3D%20Relay.createContainer(HelloApp%2C%20%7B%0A%20%20fragments%3A%20%7B%0A%20%20%20%20%2F%2F%20This%20GraphQL%20query%20executes%20against%0A%20%20%20%20%2F%2F%20the%20schema%20in%20the%20'schema'%20tab%20above.%0A%20%20%20%20%2F%2F%0A%20%20%20%20%2F%2F%20To%20learn%20more%20about%20Relay.QL%2C%20visit%3A%0A%20%20%20%20%2F%2F%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fapi-reference-relay-ql.html%0A%20%20%20%20greetings%3A%20()%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20fragment%20on%20Greetings%20%7B%0A%20%20%20%20%20%20%20%20hello%20%7B%0A%20%20%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%0A%7D)%3B%0A%0A%2F**%0A%20*%20%233%20-%20Relay%20routes%0A%20*%20Define%20a%20root%20GraphQL%20query%20into%20which%20your%0A%20*%20containers'%20query%20fragments%20will%20be%20composed.%0A%20*%0A%20*%20To%20learn%20more%20about%20Relay%20routes%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fguides-routes.html%0A%20*%2F%0Aclass%20HelloRoute%20extends%20Relay.Route%20%7B%0A%20%20static%20routeName%20%3D%20'Hello'%3B%20%20%2F%2F%20A%20unique%20name%0A%20%20static%20queries%20%3D%20%7B%0A%20%20%20%20%2F%2F%20Here%2C%20we%20compose%20your%20Relay%20container's%0A%20%20%20%20%2F%2F%20'greetings'%20fragment%20into%20the%20'greetings'%0A%20%20%20%20%2F%2F%20field%20at%20the%20root%20of%20the%20GraphQL%20schema.%0A%20%20%20%20greetings%3A%20(Component)%20%3D%3E%20Relay.QL%60%0A%20%20%20%20%20%20query%20GreetingsQuery%20%7B%0A%20%20%20%20%20%20%20%20greetings%20%7B%0A%20%20%20%20%20%20%20%20%20%20%24%7BComponent.getFragment('greetings')%7D%2C%0A%20%20%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%60%2C%0A%20%20%7D%3B%0A%7D%0A%0A%2F**%0A%20*%20%234%20-%20Relay%20root%20containers%0A%20*%20Compose%20a%20Relay%20container%20with%20a%20Relay%20route.%0A%20*%20This%20enables%20Relay%20to%20synthesize%20a%20complete%20query%0A%20*%20to%20fetch%20the%20data%20necessary%20to%20render%20your%20app.%0A%20*%0A%20*%20To%20learn%20more%20about%20Relay%20root%20containers%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Ffacebook.github.io%2Frelay%2Fdocs%2Fguides-root-container.html%0A%20*%2F%0AReactDOM.render(%0A%20%20%3CRelay.RootContainer%0A%20%20%20%20Component%3D%7BHelloApp%7D%0A%20%20%20%20route%3D%7Bnew%20HelloRoute()%7D%0A%20%20%2F%3E%2C%0A%20%20mountNode%0A)%3B%0A&schema=%2F**%0A%20*%20Copyright%20(c)%202013-present%2C%20Facebook%2C%20Inc.%0A%20*%20All%20rights%20reserved.%0A%20*%0A%20*%20This%20source%20code%20is%20licensed%20under%20the%20BSD-style%20license%20found%20in%20the%0A%20*%20LICENSE%20file%20in%20the%20root%20directory%20of%20this%20source%20tree.%20An%20additional%20grant%0A%20*%20of%20patent%20rights%20can%20be%20found%20in%20the%20PATENTS%20file%20in%20the%20same%20directory.%0A%20*%2F%0A%0Aimport%20%7B%0A%20%20GraphQLObjectType%2C%0A%20%20GraphQLSchema%2C%0A%20%20GraphQLString%2C%0A%20%20GraphQLList%2C%0A%20%20GraphQLNonNull%2C%0A%20%20GraphQLID%0A%7D%20from%20'graphql'%3B%0A%0A%0A%0A%0Aconst%20FruitType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Fruit'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20%7Btype%3A%20new%20GraphQLNonNull(GraphQLID)%7D%2C%0A%20%20%20%20name%3A%20%7Btype%3A%20GraphQLString%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0A%2F**%0A%20*%20Objects.%0A%20*%20Build%20up%20a%20portrait%20of%20your%20data%20universe%0A%20*%20using%20the%20object%20type.%20Here%2C%20we%20define%20a%0A%20*%20type%20of%20object%20that%20has%20a%20'hello'%20field%0A%20*%20that%20is%20of%20the%20string%20type.%0A%20*%2F%0Aconst%20GreetingsType%20%3D%20new%20GraphQLObjectType(%7B%0A%20%20name%3A%20'Greetings'%2C%0A%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20id%3A%20%7Btype%3A%20new%20GraphQLNonNull(GraphQLID)%7D%2C%0A%20%20%20%20hello%3A%20%7Btype%3A%20new%20GraphQLList(FruitType)%7D%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A%0A%2F**%0A%20*%20The%20schema.%0A%20*%20Here%20we%20export%20a%20schema%20that%20offers%20one%20root%0A%20*%20field%20named%20'greetings'%2C%20and%20a%20method%20to%0A%20*%20resolve%20its%20data.%0A%20*%0A%20*%20To%20learn%20more%20about%20writing%20GraphQL%20schemas%20for%20Relay%2C%20visit%3A%0A%20*%20%20%20https%3A%2F%2Fgithub.com%2Fgraphql%2Fgraphql-relay-js%0A%20*%2F%0Aexport%20default%20new%20GraphQLSchema(%7B%0A%20%20query%3A%20new%20GraphQLObjectType(%7B%0A%20%20%20%20name%3A%20'Query'%2C%0A%20%20%20%20fields%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20greetings%3A%20%7B%0A%20%20%20%20%20%20%20%20type%3A%20GreetingsType%2C%0A%20%20%20%20%20%20%20%20%2F%2F%20Here%20we%20define%20a%20resolver%20that%20returns%0A%20%20%20%20%20%20%20%20%2F%2F%20the%20data%20defined%20above.%20Were%20this%20schema%0A%20%20%20%20%20%20%20%20%2F%2F%20executing%20on%20the%20server%20side%2C%20you%20could%0A%20%20%20%20%20%20%20%20%2F%2F%20write%20a%20resolve%20method%20that%20fetches%0A%20%20%20%20%20%20%20%20%2F%2F%20live%20data%20from%20a%20database.%0A%20%20%20%20%20%20%20%20resolve%3A%20()%20%3D%3E%20(%7B%0A%20%20%20%20%20%20%20%20%20%20id%3A%20'abc'%2C%20%0A%20%20%20%20%20%20%20%20%20%20hello%3A%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20%7Bid%3A'def'%2Cname%3A'carrots'%7D%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20null%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20%7Bid%3A'gdf'%2Cname%3A'apples'%7D%0A%20%20%20%20%20%20%20%20%20%20%5D%0A%20%20%20%20%20%20%20%20%7D)%2C%0A%20%20%20%20%20%20%7D%2C%0A%20%20%20%20%7D)%2C%0A%20%20%7D)%2C%0A%7D)%3B%0A) in playground.

 Its not very neat, but should be enough to illustrate and debug issue. In console you get only array with two elements without null and server is sending three elements, with second one being null.

**Comment by josephsavona** [comment] 2016-07-01 16:50
This is by design. By design, GraphQL tends toward having fields be nullable- and given `resolve` method could fail (error, privacy check, etc). To ease client development and reduce extraneous null-checks, Relay filters null items in lists. 

We are open to re-evaluating this decision, but it is not something we can do lightly because existing clients depend on this behavior. 

Rather than rely on implicit ordering and alignment of args/results with a result type of `[Result]`, one option would be to return a wrapper object that indicates both the arg and the result: `[{args: ..., result: ?Result}]`.

**Comment by josephsavona** [comment] 2016-07-03 19:35
@jardakotesovec Thoughts?

**Comment by jardakotesovec** [comment] 2016-07-08 07:05
Thanks for explanation and sorry for delay I am on holidays this week.

I think that filtering extraneous nulls could be server responsibility (in
some middleware) or explicitly on client, but not default behavior as its
more opinionated than necessary and breaks use cases when nulls in list
would have some meaning.

Pattern I intended to use is very similar to relay plural root fields and I
think there is nothing wrong with it and in my case it makes
client implementation simpler than with approach you suggested.

Where in relay is done the filtering?

Maybe it could be some relay option? Having custom function for some
preprocessing could be also option, but not sure if that would have some
other use case. Or having fine control in fragments with @relay directive.

**Comment by josephsavona** [comment] 2016-07-08 17:35
Initially I was inclined to think that filtering nulls just makes sense overall: products will always want to filter them. But on further consideration, filtering nulls is kind of magical. This could make product development more challenging by forcing developers to deal with even more possible null values. But the ideal state would be that Relay is entirely predictable, and there are clear tools to use in managing null values (perhaps the `.?` existential operator in JavaScript and/or GraphQL support for null boundaries, etc). Relay could also respect the schema type by filtering nulls or warning/throwing if a list typed as non-null contains a null at runtime.

**Comment by theorygeek** [comment] 2016-07-08 18:42
I'd also agree that in general, Relay should _not_ filter out the null values in an array. In our schema, we also allow most of our fields to be nullable. However, fields that return an array are almost always declared as `[SomeType!]` (ie, a nullable list of non-nulls). So GraphQL is already providing a mechanism to guard against null values that occur in an array; the Relay behavior here just seems unnecessary and a bit too magical.

**Comment by jardakotesovec** [comment] 2016-07-10 20:24
Ok, to keep discussion flowing. What about

* remove null filtering from Relay
* make that use-case for list of non-nulls  more convenient server side by expressing that resolving in null does not throw but is not included in list..  roughly something like
```
new GraphQLList(GraphQLNonNull(GraphQLFloat, {}), {removeNulls: true})
```

That would guarantee client to have list of non-nulls, without worry about it at all (as it is now) and express intention clearly server side.

But not sure right now if would be important to make this pattern as part of graphql standard (for some tooling purposes?) or it could be just convenience option.

**Comment by josephsavona** [comment] 2016-07-11 00:30
Thanks for the input. We discussed this internally and all agree that filtering nulls in lists, while convenient, is unexpected/magical and shouldn't be part of the core framework. 

A tentative plan forward:
- In the next release: announce the plan to stop filtering nulls in the release notes. We should consider whether Relay should warn when it encounters a `null` in a list, this could be noisy but would at least alert developers to the fact that Relay is filtering nulls and help make them aware of the need to add null-checks where appropriate.
- In the subsequent release: remove any warnings and stop filtering nulls.

**Comment by jardakotesovec** [comment] 2016-07-11 05:40
@josephsavona Thanks, sounds good! Can you please point me where in relay is done the filtering? Just wondering if would be feasible for me to override that behavior for time being..

And what do you think about my second point - does it make sense to bring this up in graphql-js? We don't have currently such use case, but it seems to me as better option than allow null in list and filter them later on clients.

**Comment by josephsavona** [comment] 2016-07-28 15:57
@jardakotesovec This is definitely worth asking about in `graphql-js`. Note that the filtering logic is primarily in [`RelayQueryWriter`](MTQ2NzkxNTE5NA==).

I'm going to close this since it's working as designed. We are, however, taking this feedback into account for the upcoming changes to Relay core, which will not filter nulls by default. Thanks for raising this issue!

**Closed by josephsavona** 2016-07-28 15:57 UTC

**Comment by nodkz** [comment] 2016-11-01 10:39
Graphql-js now supports NULL value in args. Works like a charm!
https://github.com/graphql/graphql-js/pull/544

> 0.7.2 || >=0.8.0
