### ISSUE TITLE
forceFetch does not update the data store

### ISSUE THREAD

**Issue by gallagher-stem** [facebook/relay#874] opened 2016-02-24 01:13 UTC
I have a container that does a forceFetch when it knows (websocket) data is different on the server.  forceFetch retrieves the new data successfully, and the current container/component is re-rendered correctly with the new data, but the new data doesn't apply itself through Relay's local cache/store.  

Specifically, I am doing forceFetch on a detail page with the data for one node in a connection, but none of the connections with an edge of that node are updated with the new data.

This seems like a bug.  Relay should use a node's globalId to refresh its store with the most recently fetched data for that node.

Is there a way to get forceFetch to update the store, or is the only way to update a node throughout the store by using a mutation with a config of FIELDS_CHANGE?

**Comment by josephsavona** [comment] 2016-02-24 01:54
Thanks for asking about this. Relay uses IDs to merge new information with existing data in the store, and updates all components that are rendering records that were modified. So in general, we'd expect forceFetch to update the relevant views. Note that forceFetch will only update that specific query - if you call it from one detail component, only that component's data will update. To update all the data for a list, call forceFetch at the list level. 

We'll need a bit more detail to help us debug. What are the containers and fragments that are/aren't updating? Where are you calling forceFetch?

**Comment by gallagher-stem** [comment] 2016-02-24 02:17
Thanks for the reply.

I have one container that displays the summary information of the nodes of a connection, and then when you click on one of the nodes you get taken to another container that displays detail information about that specific node.

The list container query is `query { user }` and its fragment gets back the connection with the edges/nodes I display in the list.  The detail container query is `query { node(id: $id) }` and its fragment gets back all the fields for that node.

I am calling forceFetch from the detail view container which uses the node query.  The detail view container updates correctly when forceFetch is called, but the list container, which uses the user query, does not update its connection with the new data that was forceFetched.

**Comment by josephsavona** [comment] 2016-02-24 02:23
It sounds like the list container queries for only the list of items - something like `users(first: $n) { edges { node { ${Detail.getFragment(...)} } } }`. In that case, if some user's data updates (e.g. due to forceFetch), there are no properties to update in the list and only the detail item should/would update. 

What specific property would you expect to update in the list after the forceFetch?

**Comment by gallagher-stem** [comment] 2016-02-24 02:54
User is my Viewer, so the List fragment is more like `fragment on User {  items(first: $n)  {  edges  {  node  {  id, name, status  }  }  }`

Also, Detail is a separate container from List and not a child.  The Detail fragment is  like `fragment on Node  {  id,  ... on Item  {  name, status, all, the, things }  }`

So the specific property that updates is 'status' which is explicitly in the fragment for each container. The node's globalId is also in the fragment for each container, which is why I was thinking that Relay would be able to update its store after the forceFetch: its got a node globalId, its got new data, it should just be able to update its store by the globalId, yah?

**Comment by josephsavona** [comment] 2016-02-24 04:20
Thanks for the extra information. We'd like to help debug this issue, but we'll need more information. Given that this is such a core part of Relay functionality, I'm wondering if there is something specific about your schema, app, or configuration that is causing the view not to update appropriately in this case. For example, it could be something as innocuous as a `shouldComponentUpdate` in your app that is returning false or similar. 

Regardless, the best way to debug and find the cause is to create a minimal repro case. Is it possible to create one in the [Relay Playground](http://facebook.github.io/relay/prototyping/playground.html#/)? Alternately, what are the full fragments of the list and detail views, and the full data before/after the forceFetch?

**Comment by gallagher-stem** [comment] 2016-02-24 18:36
Thanks for the help.  I'm up against a deadline this week (launching a React + Relay app into prod) but I will throw together a repro case when I am in the clear.

**Comment by josephsavona** [comment] 2016-02-24 19:10
@gallagher-stem Sounds good. To unblock, i would recommend double-checking that you don't have a `shouldComponentUpdate` that is preventing the list/list item from re-rendering, or that you aren't somehow using the previous version of props. It's also worth checking that the ids all match up as you expect between the list and detail view.

Again, if you provide a bit more information about the container fragments and their props pre/post forceFetch we can help more.

**Comment by josephsavona** [comment] 2016-03-02 18:04
@gallagher-stem I'm going to close this issue since we know this works in the general case and don't have a good repro. If you can, please let us know some of the information mentioned above and we'll be happy to reopen and investigate.

**Closed by josephsavona** 2016-03-02 18:04 UTC

**Comment by taiki-t** [comment] 2017-08-03 04:23
> `node in a connection`

In Relay Classic, you need an object id for a root object for the connection. Otherwise it won't update the store. You might need to mock an id for a root object in server side when connection has no persisted parent (root) object.
