### ISSUE TITLE
[Modern] Longer fragment names breaks fragment composition

### ISSUE THREAD

**Issue by femesq** [facebook/relay#1692] opened 2017-04-26 02:11 UTC
Trying to use longer fragment name breaks the `QueryRendrer`:

Eg.: `QueryRenderer Query` -> `fragment ThisCanHaveLongerName on Todo`

1) Loading component is rendered "forever";
![image](https://cloud.githubusercontent.com/assets/1899668/25414914/d953935e-2a0a-11e7-83af-99f3907721ee.png)

2) `Query`'s network request never happens..

Changed `relay-examples/todo-modern` to reproduce this: https://github.com/relayjs/relay-examples/compare/master...femesq:master

Also had similar problem when 2 components live aside in same file... Althought compiler seens to generate `__generated__` files correctly:
![image](https://cloud.githubusercontent.com/assets/1899668/25415143/38b6c07c-2a0c-11e7-88fe-5eaf4da33c1e.png)

Is there any limitation on having multiples fragments in same file?

**Comment by josephsavona** [comment] 2017-04-26 14:39
Hey, thanks for reporting this. Multiple fragments in a container are supported, and the length of the fragment name shouldn't matter so long as it matches the expected pattern (FileName_propName if you have multiple fragments, otherwise FileName for a single fragment). 

What rc version are you using? Also, can you check the browser console and paste whatever error is printed there here so we can determine the cause of the problem?

**Comment by femesq** [comment] 2017-04-26 17:24
That's the point.. Since it renders the default render (usually a `<Loading />` component, since it don't get the `props`), it fails silently, so no errors or warnings on console.

In this reproduction I've used the version on [package.json](https://github.com/femesq/relay-examples/blob/master/todo-modern/package.json), but in my project I'm on `rc.1`... Can try this reproduction code on `rc.2` too, if it helps...

**Comment by josephsavona** [comment] 2017-04-26 19:56
I see. I'm pretty sure that this is a duplicate of #1665, which is fixed on master and will go out with RC3.

**Comment by femesq** [comment] 2017-04-26 22:22
Great to know this!
Will keep watching there and wait for RC.3 release.. If I got some time, will try it with master and post results here...
Thanks!

**Comment by femesq** [comment] 2017-04-27 13:04
Still broken on[rc.3]...

**Comment by yuzhi** [comment] 2017-09-11 17:41
Sorry for taking to long to get back to this. We are trying to clean up the issues in this repo. @femesq can you reopen the issue if this is still broken for you?

**Closed by yuzhi** 2017-09-11 17:41 UTC
