### ISSUE TITLE
Edge returns from mutation without typename

### ISSUE THREAD

**Issue by steveluscher** [facebook/relay#653] opened 2015-12-06 02:26 UTC
Repro:

1. Load the TodoMVC example
2. Create a new todo

```
Warning: RelayQueryWriter: Could not find a type name for record `client:client:17244854812:VG9kbzoxMA==`.
```

Should we add `__typename` as a requisite field everywhere for mutation queries?

**Comment by josephsavona** [comment] 2015-12-06 05:35
We should be already adding `__typename` wherever there is an abstract type. I can look into this.

**Comment by josephsavona** [comment] 2015-12-07 00:27
closing as a duplicate of #474.

**Closed by josephsavona** 2015-12-07 00:27 UTC
