### ISSUE TITLE
undefined is not a function (evaluating 'connectionInfo[typeOf Symbol === 'function'? Symbol.iterator:'@@iterator']()')

### ISSUE THREAD

**Issue by ryanmcclure4** [facebook/relay#2371] opened 2018-03-16 02:11 UTC
I'm getting this error in react-native, using react-relay 1.5.0 and relay-runtime 1.5.0. It is being thrown when an optimistic update is being applied for my mutation. I've found similar issues being reported on react-native with other packages, but none of them came to a conclusion as to why it's happening or how to solve it.

![image](https://user-images.githubusercontent.com/9887662/37500089-c3415398-2884-11e8-9ee0-fe8f0cf18376.png)

It seems to be related to transpilation, as this is occurring in a transpiled for...of loop - but I don't have any problems running this code outside of react-native. Any ideas?

**Comment by zth** [comment] 2018-03-18 10:16
Does this happen on both iOS and Android? I vaguely recall having an issue like this before only on Android, which was related to needing to apply a polyfill (can't remember which, maybe es6 Set or Symbol) before anything else loads in the bundle. This might not at all be the issue and it only occurred on Android IIRC, but maybe worth a shot.

**Comment by ryanmcclure4** [comment] 2018-03-18 14:36
@zth Sounds like you had the same exact issue - this works without any problems on iOS. I've tried adding `import 'es6-symbol/implement'` and `import 'babel-polyfill'` to my index.android.js file, both with no luck. Can you recall which polyfill you used and where you added it?

**Comment by sibelius** [comment] 2018-03-18 15:03
This is fixed on latest version of React-Native

**Comment by zth** [comment] 2018-03-18 15:44
@ryanmcclure4 sure! This is the extra stuff I've added on Android:

```
import 'core-js/es6/symbol';
import 'core-js/es6/array';
import 'core-js/es6/string';
```

Like I said, not sure if that's the problem, but I do vaguely recall experiencing something similar...

**Comment by ryanmcclure4** [comment] 2018-03-18 15:57
@sibelius I'm currently using the latest version of react-native (0.54.2)...

@zth Thanks for sharing! Though I just added it, and ironically I'm now getting the same error even sooner in execution. It's now being called when setting the relay environment in RelayModernEnvironment.js. I added these imports in my index.android.js file -- You said you put it before anything else loads in your bundle...was that in some other file?

**Comment by zth** [comment] 2018-03-18 16:06
@ryanmcclure4 Hmm! Maybe this wasn't the fix then after all. Well, adding it at the top of `index.android.js` should do the trick if this indeed was the issue, as nothing else will have been imported before the polyfills. 

I'm not on the latest Relay though (I'm on 1.4.1) nor the latest React Native (on 0.53.3), maybe that affects the issue? Did you try downgrading Relay just to see if the issue is introduced for you in 1.5.0?

I've looked through my code again and I have no other polyfills applied. My `.babelrc` contains nothing unusual either. Have you tried the good ol' delete-and-reinstall-node-modules after doing the changes? Grasping at straws here, but it has solved weird issues before ;)

**Comment by ryanmcclure4** [comment] 2018-03-18 16:50
Unfortunately I've also tried with relay 1.4.1 and just tested with rn 0.53.3 as well, but with no luck. I run `rm -rf node_modules && npm i` so often it hurts :P

**Comment by ryanmcclure4** [comment] 2018-03-18 18:46
I'm able to fix it temporarily by replacing the transpiled for...of loop with a generic for loop iterating over the array:

```
// for (var _iterator = connectionInfo[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
//    var info = _step.value;

for (var i = 0; i < connectionInfo.length; i++) {
    var info = connectionInfo[i];
```

So in the meantime I'll just fork relay-runtime and replace all the for...of loops. Not ideal, but I'm tired of messing with endless combinations of polyfills lol.

**Comment by jstejada** [comment] 2018-03-19 01:55
This doesn't seem to be an issue pertaining specifically to Relay so I'm closing it for now, feel free to re-open if that isn't the case.

Thanks!

**Closed by jstejada** 2018-03-19 01:55 UTC
