### ISSUE TITLE
Fields in different subtypes with same name not retrieved on mutation

### ISSUE THREAD

**Issue by luisobo** [facebook/relay#596] opened 2015-11-13 16:59 UTC
I have an interface Customization and several object types implementing this interface, three of the subtypes have a field called iconUrl but they mean different things depending on the concrete type in which they are. They just happen to be called the same. These fields have no arguments, but we may add them in the future.

```
interface Customization {
  customizableId: String!
}

type ShowIconInTitle: Customization {
  iconUrl: Url
  ...
}

type ShowSomethingElseSomewhereElse: Customization {
  iconUrl: Url
  ...
}

type SomeOtherWithoutIcon: Customization {
  ...
  // no iconUrl here
}
```
when querying for all the Customizations of a given customizable, the query looks like this:
```
fragment on Customizable {
        id,
        ${AddShowIconInTitleCustomizationToNodeMutation.getFragment('customizable')},
        ${AddShowSomethingElseSomewhereElseCustomizationToNodeMutation.getFragment('customizable')},
        ${AddSomeOtherWithoutIconCustomizationToNodeMutation.getFragment('customizable')},
        ${RemoveCustomizationFromNodeMutation.getFragment('customizable')},
        customizations {
          customizableId,
          kind,
          ${ShowIconInTitleCell.getFragment('customization')},
          ${ShowSomethingElseSomewhereElseCell.getFragment('customization')},
          ${SomeOtherWithoutIconCell.getFragment('customization')},
        }
      }
```
What happens is that only the iconUrl of the first subtype listed in the query above gets requested to the server during the Add mutation. In this case, if I add a ShowIconInTitle, the iconUrl gets requested fine as part of the mutation, because it is the first in the list, but if I do add a ShowSomethingElseSomewhereElse, the iconUrl of that subtype does not get requested to the server as part of the mutation.

When refreshing the entire page all the fields come back just fine. I workaround this issue with forceFetching the component after the mutation

These are my deps:
```
    "babel-core": "^5.8.25",
    "babel-loader": "^5.3.2",
    "babel-relay-plugin": "^0.4.1",
    "graphql": "^0.4.4",
    "history": "^1.12.6",
    "node-uuid": "^1.4.3",
    "react": "^0.14.0",
    "react-dom": "^0.14.0",
    "react-relay": "^0.5.0",
    "react-router": "^1.0.0-rc3",
    "react-router-relay": "^0.7.0",
    "sync-request": "^2.0.1",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.1"
```

Hope this helps.

**Comment by josephsavona** [comment] 2015-11-13 17:28
Thanks for filing this. This is caused by queries being flattened prior to creating the mutation query. 

Cc @yungsters - we should flatten only the optimistic query.

**Comment by josephsavona** [comment] 2015-11-29 19:10
@luisobo #627 fixes this and should land in master soon.

**Comment by josephsavona** [comment] 2015-12-02 02:14
The fix landed - thanks @luisobo for reporting this!

**Closed by josephsavona** 2015-12-02 02:14 UTC
Labels: bug
