### ISSUE TITLE
Relay 0.5.0 invariant expects query to be empty, 0.4.0 worked fine

### ISSUE THREAD

**Issue by LegNeato** [facebook/relay#585] opened 2015-11-11 22:37 UTC
Getting this error with Relay 0.5.0:

```js
Uncaught Invariant Violation: Relay.QL: Expected query `onboarding_data` to be empty. For example, use `node(id: $id)`, not `node(id: $id) { ... }`.
```
Everything worked fine with 0.4.0. I have the latest GraphQL and React.

Not sure what info you need to debug or if the issue is on my side and 0.4.0 is more tolerant...let me know what you need.

**Comment by josephsavona** [comment] 2015-11-11 22:50
@LegNeato can you paste your route definition?

**Comment by LegNeato** [comment] 2015-11-11 22:58
I'm using `react-router` and `react-router-relay` so there is likely magic going on under the hood I am not aware of. This is how I have it configured anyway, not sure it helps...

```js
const OnboardingDataQueries = {
  onboarding_data: (Component) => Relay.QL`
    query {
      onboarding_data {
        ${Component.getFragment('onboarding_data')},
      },
    }
  `,
};
```

```js
<Route path="/account/setup/type" component={AccountTypeOnboardingPage} queries={OnboardingDataQueries} />
```

```js
...
  static fragments = {
    onboarding_data: () => Relay.QL`
      fragment on OnboardingData {
        id,
        accountType,
      }
    `,
  };
}

export default Relay.createContainer(AccountTypeOnboardingPage, {
  fragments: {
    onboarding_data: () => Relay.QL`
      fragment on OnboardingData {
        id,
        accountType,
        ${AccountTypeOnboardingMutation.getFragment('onboarding_data')},
      }
    `,
  },
});

**Comment by josephsavona** [comment] 2015-11-11 23:13
@LegNeato what browser are you using? Relay checks the function length to see whether it takes arguments - your query definition (``(Component) => Relay.QL`...` ``) takes an argument, but the fn.length check seems to be returning 0 instead of 1.

**Comment by kassens** [comment] 2015-11-11 23:18
Could you paste what the code looks like transformed? Maybe it's the way the arrow function is transformed in your pipeline that breaks this detection?

**Comment by LegNeato** [comment] 2015-11-11 23:20
@josephsavona latest Chrome. Attached is a (crappy) screenshot with values from the debugger.

<img width="1787" alt="screen shot 2015-11-11 at 3 19 42 pm" src="https://cloud.githubusercontent.com/assets/368904/11106016/ac547fba-8887-11e5-88cf-98eaa4c45814.png">

**Comment by josephsavona** [comment] 2015-11-11 23:22
From the screenshot, it appears that `queryBuilder` is a function with zero arguments. Can you paste the transformed code for your route?

**Comment by kassens** [comment] 2015-11-11 23:28
The call to `isDeprecatedCallWithArgCountGreaterThan(queryBuilder, 0)` is supposed to return false since your `queryBuilder` has 1 argument. `queryBuilder` is the arrow function defined here in your code:

```javascript
const OnboardingDataQueries = {
  onboarding_data: (Component) => Relay.QL`...`
}
```

...and it has 1 argument. How does the arrow function look like transformed?

**Comment by LegNeato** [comment] 2015-11-11 23:30
```js
var OnboardingDataQueries = {
  onboarding_data: function onboarding_data(Component) {
    return (function (sub_0) {
      return {
        children: [{
          fieldName: 'id',
          kind: 'Field',
          metadata: {
            parentType: 'OnboardingData',
            isGenerated: true,
            isRequisite: true
          }
        }, _reactRelay2['default'].QL.__frag(sub_0)],
        fieldName: 'onboarding_data',
        kind: 'Query',
        metadata: {},
        name: 'App'
      };
    })(Component.getFragment('onboarding_data'));
  }
};
```

FWIW I'm using pretty standard babel (5, not 6) and webpack AFAIK. But I am a JS n00b :-D.

**Comment by LegNeato** [comment] 2015-11-11 23:36
<img width="753" alt="screen shot 2015-11-11 at 3 36 15 pm" src="https://cloud.githubusercontent.com/assets/368904/11106314/fed3e724-8889-11e5-83c5-d827abd41155.png">

**Comment by LegNeato** [comment] 2015-11-11 23:42
`children` here has 2 elements, and one is not a `Field` (it is a `RelayFragmentReference`) which appears to make the `children.every()` fail.

<img width="732" alt="screen shot 2015-11-11 at 3 42 14 pm" src="https://cloud.githubusercontent.com/assets/368904/11106415/d32795e8-888a-11e5-94b7-0bbc63c08e55.png">

**Comment by josephsavona** [comment] 2015-11-11 23:45
This looks like a problem with `react-router-relay` - the function `onboarding_data` is being wrapped as

```javascript
function() {
  return query(component, routeParams);
}
```

**Comment by LegNeato** [comment] 2015-11-11 23:59
Cool, do you want me to close this out or is it a behavior/expectation change that needs to be reverted in relay?

**Comment by taion** [comment] 2015-11-12 00:04
I think I just need to update this on my side.

**Comment by taion** [comment] 2015-11-12 00:14
Although I am curious what changed.

**Comment by josephsavona** [comment] 2015-11-12 00:38
This is expected behavior for Relay; `react-relay-router` shouldn't wrap the query builder (``(Component) => Relay.QL``). The change in Relay was to remove support for a deprecated form of query builders that accepted 3 arguments (not used in open source).

**Comment by josephsavona** [comment] 2015-11-12 00:41
@taion We made the check slightly more strict here: https://github.com/facebook/relay/commit/c9baf7f19a05b20bed6474d14fdbc8e3111e913e#commitcomment-14343423

**Comment by taion** [comment] 2015-11-12 00:45
Thanks! I'm going to roll this fix on my side into part of a broader fix now that I have some new APIs available on the React Router side as well. Should have this fixed soon.

**Comment by kassens** [comment] 2015-11-12 00:51
@LegNeato for your case the shorthand version might fix your immediate issue (at least for this case):

```javascript
const OnboardingDataQueries = {
  onboarding_data: () => Relay.QL`
    query {
      onboarding_data
    }
  `,
};
```

**Comment by josephsavona** [comment] 2015-11-12 01:08
Sounds good, i'll close this out but feel free to continue the discussion here.

**Closed by josephsavona** 2015-11-12 01:08 UTC
