### ISSUE TITLE
How does relay build the entire graphql query from the component tree?

### ISSUE THREAD

**Issue by ccorcos** [facebook/relay#1460] opened 2016-11-30 21:29 UTC
I'm trying to figure out how Relay is fundamentally able to take a component tree and extract the graphql query. I tried looking though here and didnt get very far: https://github.com/facebook/relay/blob/master/src/container/RelayContainer.js

I think a very minimal example is something like this:

```js
import React, { PureComponent } from 'react'

class Something extends Component {
  render() {
    return (
      <div>
        something
      </div>
    )
  }
}

Something = createContainer(Something, {
  tree: () => ({
    a: 1,
  })
})

class TwoSomething extends Component {
  render() {
    return (
      <div>
        <Something/>
        <Something/>
      </div>
    )
  }
}

TwoSomething = createContainer(TwoSomething, {
  tree: () => ({
    one: Something.getTree(),
    two: Something.getTree(),
  })
})
```

In the spirit of Relay, it seems like I should be able to have a provider container of sorts that should be table to read the entire tree out which should look something like `{one: {a: 1}, two: {a: 1}}`.

Then there's variables and stuff, but lets not get ahead of ourselves. Any ideas or suggestions how this works? I'd like to make something similar.

**Comment by yachaka** [comment] 2016-12-03 11:45
@ccorcos Query composition is done using [graphql fragments](http://graphql.org/learn/queries/#fragments). By including fragments into fragments, each container can compose from childs and the RootContainer will include that fragment into a query which will be sent to the server.
I don't understand exactly what you are trying to understand, so please specify If I didn't answer well !

**Comment by josephsavona** [comment] 2016-12-03 18:48
In a nutshell, each Relay.QL tag transforms to a function that returns an object:

https://github.com/facebook/relay/blob/master/scripts/babel-relay-plugin/src/__fixtures__/fragmentWithReference.fixture

Fragment references are function calls whose return value is embedded in the object (see the Relay.QL.__ref call and how `reference` Is handled), so it's ultimately not too different from:

```
function parent() {
  return {
    child: child(),
  };
}
function child() {
  return ...
}
```

I'm going to close this since it's not a bug or open question, but feel free to ask follow up questions and I'll answer as time permits!

**Closed by josephsavona** 2016-12-03 18:48 UTC
Labels: question

**Comment by ccorcos** [comment] 2016-12-04 20:55
@yachaka @josephsavona the Relay containers have state variables though. So it's not as simple as calling a static method that returns the entire query, you need to be able to get the tree as a function of the application state. So that's more of my question -- how do the variables work?

**Comment by josephsavona** [comment] 2016-12-04 23:27
Queries are effectively decoupled from application state. For variables, check out RelayQuery, RelayFragmentReference, etc. Initial variables are handled similarly to the `child` function above pulling values (vars) from its JavaScript closure.

**Comment by ccorcos** [comment] 2016-12-05 19:31
Interesting... I see. So you give some initial variables, and then just call `setVariables` whenever you want to change a variable and all this context stuff wires everything together. And since everything is asynchronous, it all works out. 

Now I could be wrong, but I find this to be an odd strategy. It seems to me like Relay could potentially work just like React works for rendering:

```js
class Something extends PureComponent {
  query() {
    return Relay.QL` ... ` // you can use this.props or this.state here
  }
  render() {
    return <div>...</div> // you can use this.props or this.state here as well
  }
}
```

Instead there's this whole stateful dance under the hood where Relay containers talk to each other through contexts. Is there any reason why the approach above wouldn't work? It just seems a lot simpler to me and I'd imagine React has already done much of the legwork to make that happen.

**Comment by josephsavona** [comment] 2016-12-05 21:22
Good questions. A lot of the complexity in Relay is not obvious if you haven't tried to build something like it. For example, it's easy to forget that props *are the results of queries*, so you can't have a `query()` function that depends on props/state (as in your example) or rely on React lifecycle methods for updating/constructing them.

If you're interested in how Relay 0.9 works, i'd highly recommend watching @wincent's talk: https://facebook.github.io/relay/docs/videos.html#relay-deep-dive-slides-https-speakerdeck-com-wincent-relay-deep-dive (there's a video or annotated slides)

**Comment by ccorcos** [comment] 2016-12-06 00:18
> For example, it's easy to forget that props are the results of queries, so you can't have a query() function that depends on props/state (as in your example) or rely on React lifecycle methods for updating/constructing them.

Oy. What a nightmare. Do you see what I'm getting at about the how Relay variables are not directly derived anywhere though? It seems to me that if we were to rework things so that the relay data was pulled out the props, then we'd have two very nice function signatures: `(props, data, state) => vdom` and `(props, state) => query`. Although I'm seeing what you mean about the lifecycle... Dang.

I'll check out that video though, and thanks for the help, I really appreciate it. :)

**Comment by josephsavona** [comment] 2016-12-06 01:46
Yeah, `(props, state) => query` unfortunately does not make sense given that props are the results of the query.

**Comment by ccorcos** [comment] 2016-12-12 00:33
Well there is inherently a difference between props that come from relay, and props that are set by the parent component...
