### ISSUE TITLE
Relay constructing wrong query when querying for missing fields on a connection

### ISSUE THREAD

**Issue by KyleAMathews** [facebook/relay#305] opened 2015-09-14 03:07 UTC
I have one component with this query fragment:

```
    viewer: () => Relay.QL`
      fragment on User {
        id
        allPosts(first: 5) {
          edges {
            node {
              title
            }
          }
        }
      }
    `
```

If I click from that component to another one that has the same query except it also asks for the body field e.g.:

```
    viewer: () => Relay.QL`
      fragment on User {
        id
        allPosts(first: 5) {
          edges {
            node {
              title
              body
            }
          }
        }
      }
    `
```

Relay then sends in parallel 5 queries that look like:
`{ query: 'query Router{node(id:"UG9zdDo1MA=="){body,id}}`​

This errors as the `Node` type doesn't have a body field.

**Comment by josephsavona** [comment] 2015-09-14 03:15
Thanks for reporting this. It looks like `diffRelayQuery()` isn't taking into account the parent type.

**Comment by KyleAMathews** [comment] 2015-09-14 03:15
Cool, good to know it's not me this time :)

**Comment by josephsavona** [comment] 2015-09-15 21:26
@KyleAMathews thanks again for reporting this - the issue is now fixed on master, i'm going to close.

**Closed by josephsavona** 2015-09-15 21:26 UTC

**Comment by KyleAMathews** [comment] 2015-09-15 21:30
Thanks for the fix! Also great talk yesterday @scale. Watched it this
morning.

**Comment by josephsavona** [comment] 2015-09-16 00:04
thanks! :-)
