### ISSUE TITLE
Warning that injecting a network layer would overwrite a previously injected layer

### ISSUE THREAD

**Issue by soosap** [facebook/relay#1122] opened 2016-05-06 15:57 UTC
Since **0.8.1** I am receiving this new warning >> `Warning: RelayNetworkLayer: Call received to injectImplementation(), but a layer was already injected.` << when I try to inject my default network layer. I want to separate my GraphQL server from my React/Relay app. I have not injected any other network layer before that. Relay seems to do this by default.

```js
Relay.injectNetworkLayer(
  new Relay.DefaultNetworkLayer(process.env.GRAPHQL_ENDPOINT)
);
```
What is the right way to go about it to avoid this warning?

**Comment by wincent** [comment] 2016-05-06 16:39
This is fixed and will be resolved in the next release (see #1111). Sorry about the noise, and thanks for the report!

**Closed by wincent** 2016-05-06 16:39 UTC

**Comment by sedubois** [comment] 2016-10-25 14:30
@wincent I still see this warning when using `Relay.injectNetworkLayer(new Relay.DefaultNetworkLayer(url, options))` with `react-relay@0.9.3`.

**Comment by wincent** [comment] 2016-10-25 14:44
@sedubois: That suggests that a layer was already injected. Would need to see some code to troubleshoot further.

**Comment by sedubois** [comment] 2016-10-25 15:05
Yes, a layer was already injected, but I want to update the headers after user authentication. The code is [here](https://github.com/sedubois/belong/blob/gql-auth/app/relay/index.js).

**Comment by wincent** [comment] 2016-10-25 15:12
> a layer was already injected

Then everything is working as intended. This is why this is a warning and not an error. The purpose is to help people avoid overwriting a layer by mistake (this actually happened at FB, when two separate teams had their own competing layers in a shared context) but still allow people who have a legitimate reason for injecting more than once to do so, albeit with a warning.

If the warning is truly obnoxious to you then we could look at adding a `force` kind of flag to effectively suppress the warning.

**Comment by sedubois** [comment] 2016-10-25 15:26
> This is why this is a warning and not an error

It's actually an error (red and still appears when filtering only for Errors in chrome console):

<img width="1258" alt="screen shot 2016-10-25 at 18 22 33" src="https://cloud.githubusercontent.com/assets/4217871/19692298/1767389a-9ae0-11e6-9f41-c4992f3f9bce.png">

> If the warning is truly obnoxious to you then we could look at adding a force kind of flag to effectively suppress the warning.

That would be really welcome, yes 😊 I believe the scenario I described is valid and common, and should therefore not pollute the console.

**Comment by wincent** [comment] 2016-10-25 15:31
It uses `warning` ([here](https://github.com/facebook/relay/blob/17096c3f22fbd98d0b4ace26762917e6c6a54832/src/network/RelayNetworkLayer.js#L67)). Seems like that ends up calling `console.error`. Feel free to submit a PR.
