### ISSUE TITLE
Bug in Todo example likely related to connections

### ISSUE THREAD

**Issue by kassens** [facebook/relay#873] opened 2016-02-24 00:18 UTC
I haven't dug more into this yet, just documenting this issue here.

Repro:
1. Run the todo example
2. Go to http://localhost:3000/#/active
3. Mark all todos as done
4. Reload (still on `/active`), notice it correctly displays no more active todos
5. Switch to the completed tab and notice it's empty (it shouldn't be)
6. Reload `/completed` and notice it now displays the completed todos. (switching to the "All" tab correctly displays the todos)

**Comment by josephsavona** [comment] 2016-02-24 00:23
duplicate of #871

**Comment by josephsavona** [comment] 2016-02-24 00:24
Actually, this is a bug specific to the todo app, let's track here.

**Comment by r0b1n** [comment] 2016-02-24 00:59
I done some digging on it, and it is not easy to make list right. As I understand, with current API it is not possible to insert element to specific place/index with `RANGE_ADD`, we may only append/prepend/remove elements. 
For example in todo we expect what todos will be in one order under different filters. While performing `RANGE_ADD` we actually don't know where to place new element.

Imagine we have 3 of todos 
```
All:
[+] item 1
[ ] item 2
[+] item 3
```

Under Completed filter we see:
```
Completed:
[+] item 1
[+] item 3
```

But what of we marking `item 2` as completed, we may expect it should be the same order as all items, right?
```
Completed:
[+] item 1
[+] item 2
[+] item 3
```

But we can't achieve this, we may do only `append` or `prepend`
```
Completed:
[+] item 1
[+] item 3
[+] item 2

// or 

[+] item 2
[+] item 1
[+] item 3
```

While All list remains in this order:
```
All:
[+] item 1
[+] item 2
[+] item 3
```
So it makes weird effect, items are jumping while switching filter.

I think filtering like this is likely use case and issue related to Relay and its API as well.

**Comment by kassens** [comment] 2016-02-24 01:18
One thing that seems very suspicious is that this `instanceof` check is false in `database.js`:

```javascript
var todo = new Todo();
console.log(todo instanceof Todo); // false, wtf?
```

This causes a `node` call to return `null` when it shouldn't.

**Comment by kassens** [comment] 2016-02-24 01:22
Looks like we just have to remove the `extends Object` from `Todo` and `User`. Will test that later.

**Comment by r0b1n** [comment] 2016-02-24 01:32
@kassens I think it is babel related https://phabricator.babeljs.io/T6964

**Comment by kassens** [comment] 2016-02-24 07:58
Thanks @r0b1n, that's exactly it.

**Closed** 2016-02-26 01:31 UTC
Labels: bug
