### ISSUE TITLE
query parameters changing input types when converted to node queries

### ISSUE THREAD

**Issue by ts-smith** [facebook/relay#61] opened 2015-08-13 20:56 UTC
Not certain if this is a bug, but...

Modifying the TodoApp container in the todo example like this (ignoring the ...on User part):

```
export default Relay.createContainer(TodoApp, {
  initialVariables: {
    cursor: null
  },
  fragments: {
    viewer: () => Relay.QL`
      fragment on User {
        ...on User {
          todos(first: 4, after: $cursor) {
            edges {
              cursor,
              node {
                id,
              },
            },
            totalCount,
            ${TodoList.getFragment('todos')},
            ${TodoListFooter.getFragment('todos')},
          }
        }
        ${AddTodoMutation.getFragment('viewer')},
        ${TodoList.getFragment('viewer')},
        ${TodoListFooter.getFragment('viewer')},
      }
    `,
  },
});
```

results in a node query with a subcomponent like this (when the cursor is change):

...`_todosdf82087a:todos(after:\"YXJyYXljb25uZWN0aW9uOjM=\",first:\"4\")`...

resulting in the error: 

```
{
  "errors": [
    {
      "message": "Argument \"first\" expected type \"Int\" but got: \"\"4\"\".",
      "locations": [
        {
          "line": 1,
          "column": 665
        }
      ]
    }
  ]
}
```

**Comment by josephsavona** [comment] 2015-08-13 22:25
Thanks for reporting this and making the error so clear. This is actually a duplicate of #40, so I'm going to close it out and track progress there.

**Closed by josephsavona** 2015-08-13 22:25 UTC
