### ISSUE TITLE
useLazyLoadQuery breaks with GC after quick unmount -> mount

### ISSUE THREAD

**Issue by saivann** [facebook/relay#3298] opened 2020-12-17 23:36 UTC
useLazyLoadQuery is returning undefined without refetching when the following occurs:

1. A component using useLazyLoadQuery mounts and eventually unsuspends.
2. This component is then unmounted in one place to be mounted in a separate spot in the JSX.

The following error warning is printed in the console:

```
Warning: Relay: Expected to have been able to read non-null data for fragment
`ProofOfBugQuery` declared in `useLazyLoadQuery()`, since fragment reference 
was non-null. Make sure that that `useLazyLoadQuery()`'s parent isn't holding on
to and/or passing a fragment reference for data that has been deleted.
```

This problem is not occuring when garbage collection is disabled, either by running environment.retain() on that query or by setting a large gcReleaseBufferSize in the provider.

Here is a runnable example to reproduce the bug:

```
import React, { useEffect, Suspense, useState } from 'react';
import { graphql, useLazyLoadQuery } from 'react-relay/hooks';

const Content = ({ onMount }) => {
  const data = useLazyLoadQuery(
    graphql`
      query ProofOfBugQuery {
        viewer {
          x
        }
      }
    `,
    {},
  );

  useEffect(() => {
    onMount();
  }, []);

  return <div>{data ? 'Loaded' : 'ERROR, data is undefined'}</div>;
};

const ProofOfBug = () => {
  const [switched, setSwitched] = useState(false);

  const onMount = () => {
    setTimeout(() => setSwitched(true), 1000);
  };

  return (
    <Suspense fallback="Loading">
      <div>{switched ? null : <Content onMount={onMount} />}</div>
      <div>{switched ? <Content onMount={onMount} /> : null}</div>
    </Suspense>
  );
};

export default ProofOfBug;
```

This is the version of Relay in use:

```
    "relay-compiler": "10.1.0",
    "relay-compiler-language-typescript": "13.0.2",
    "relay-config": "10.1.0",
    "react-relay": "0.0.0-experimental-c818bac3",
    "relay-runtime": "10.1.0",
```

Hopefully this bug report is understandable. Please let me know if I can provide any more helpful information!

**Comment by imownbey** [comment] 2021-01-04 21:28
Possibly related to #3215 and #3270 ?

**Comment by imownbey** [comment] 2021-01-05 17:11
Seems like maybe this is being called https://github.com/facebook/relay/blob/2b77b4b0280a670f9ca04b6b224a539c41935d17/packages/relay-experimental/QueryResource.js#L310 but gets short circuited by https://github.com/facebook/relay/blob/2b77b4b0280a670f9ca04b6b224a539c41935d17/packages/relay-experimental/QueryResource.js#L167-L169 ?

**Comment by imownbey** [comment] 2021-01-05 21:06
Here is a repo that reproduces the issue (you need to add your github key to the environment) https://github.com/imownbey/relay-examples. Note how I had to comment out https://github.com/imownbey/relay-examples/blob/master/issue-tracker/src/RelayEnvironment.js#L62 to make it throw the error

**Comment by imownbey** [comment] 2021-01-05 23:18
It also seems to only happen ~50% of the time which kind of makes sense?

**Comment by jstejada** [comment] 2021-01-15 17:25
thanks for reporting @saivann and @imownbey, I'm going to look into this. quick question, are you using concurrent mode when this happens, or not?

**Comment by saivann** [comment] 2021-01-15 17:28
@jstejada Thank you!! All the examples we provided did *not* use concurrent mode. Please let us know if we can do anything to help further. :pray:

**Comment by jstejada** [comment] 2021-01-15 17:48
@saivann, to confirm, did this problem start happening when you upgraded relay?

**Comment by saivann** [comment] 2021-01-15 18:04
@jstejada We started using Relay on `0.0.0-experimental-c818bac3` (the version on which we reproduced this problem) so we do not know if this is a regression or long term bug in the library.

**Comment by saivann** [comment] 2021-01-15 20:52
react and react-dom are locked to `16.13.1` in yarn.lock

**Comment by saivann** [comment] 2021-02-05 12:51
@jstejada Were you able to reproduce / find the cause? @imownbey provided a repo example of the problem [here](https://github.com/facebook/relay/issues/3298#issuecomment-754899281) in case it helps.

**Comment by jstejada** [comment] 2021-02-05 14:24
hey, not yet, but working on it

**Comment by jstejada** [comment] 2021-02-08 23:20
i was able to reproduce and have a change that should be landing today or tomorrow

**Comment by jstejada** [comment] 2021-02-10 17:14
@saivann  @imownbey, this should be fixed with 24bac58f46bc7694f069e46c4493201dfea60786, so closing this issue

**Closed by jstejada** 2021-02-10 17:14 UTC

**Comment by saivann** [comment] 2021-02-11 16:09
@jstejada Thank you so much! Seems like this commit is not yet published to npm for relay-experimental? Any advice on how we can update and test?

**Comment by jstejada** [comment] 2021-02-12 05:18
we haven't cut a new experimental release, will let you know when we do

**Comment by Charles-Johnson** [comment] 2023-02-28 16:09
I'm still experiencing `useLazyLoadQuery` returning `undefined` in v13 although it's been hard to reproduce

**Comment by anatooly** [comment] 2023-08-10 10:14
ERROR  Warning: Relay: Expected to have been able to read non-null data for fragment `FRAGMENT_NAME` declared in `useFragment()`, since fragment reference was non-null. Make sure that that `useFragment()`'s parent isn't holding on to and/or passing a fragment reference for data that has been deleted. 
 
"react-relay": "^14.1.0",
