### ISSUE TITLE
relay-compiler: config of customScalars for accurate flow types

### ISSUE THREAD

**Issue by ckknight** [facebook/relay#2162] opened 2017-10-20 21:03 UTC
I have a custom scalar on my backend called `DataUrl` which is just a string which has been validated to be a `data:` url.

In https://github.com/facebook/relay/blob/master/packages/relay-compiler/bin/RelayCompilerBin.js#L177, `customScalars` is passed as an empty object, but could be configuration-based.

It is used by https://github.com/facebook/relay/blob/master/packages/relay-compiler/core/RelayFlowTypeTransformers.js#L74. There appears to be special support for the nonstandard `Url` scalar type already.

**Comment by mike-marcacci** [comment] 2017-11-15 03:24
It appears that this is a duplicate of #1874, which is closed but still relevant.

I would like to note, though, that simple configuration of the serialized data type probably isn't sufficient. Given that custom scalars might be hydrated into any given type via a handler (see #91, which should also be reopened) we would ideally have the ability to hook into the flow types declared elsewhere in the app.

Perhaps the real solution requires [customizing the compiler](https://facebook.github.io/relay/docs/relay-compiler.html#advanced-usage), or maybe building a compiler plugin (is this a thing?) as alluded to here:
https://github.com/facebook/relay/blob/51e8b54b2866576d2c28761febaace1854e3ad0d/packages/relay-compiler/graphql-compiler/core/GraphQLParser.js#L87-L92

**Comment by jkimbo** [comment] 2018-01-27 19:04
In my opinion the cleanest solution would be to allow configuration of this field in `relay-compiler`: https://github.com/facebook/relay/blob/5b8040a4c63495a7313f88bf9124fbca8944f521/packages/relay-compiler/bin/RelayCompilerBin.js#L189

Since its not something that could easily be passed through command line args, would the relay maintainers accept a PR that added something like https://github.com/davidtheclark/cosmiconfig to relay-compiler so that users can have more control over the options?

**Comment by alloy** [comment] 2018-08-21 10:16
Related https://github.com/facebook/relay/issues/2518

**Comment by josephsavona** [comment] 2019-01-10 17:02
#2518 is a potential solution to this but further off. We'd be happy to support adding a command-line flag for populating `customScalars` (`--custom-scalar <customname>=<graphqlname>` and allow the flag to be repeated). @ckknight interested in sending a PR?

**Comment by mike-marcacci** [comment] 2019-01-10 17:08
For what it's worth, the Apollo codegen provides an option to names the flow type of custom scalars using the GraphQL name and an optional prefix. So for example, if I had a custom scalar called `PolygonCoordinates` and a prefix for these called `GraphQL$` it would use `GraphQL$PolygonCoordinates` as the flow type.

This allows me to define a global `GraphQL$PolygonCoordinates` in my root libdef and be done with it. Using globals doesn't exactly give me the warm fuzzies, but it's a really effective, easy-to-implement solution that properly fixes the problem.

**Comment by sibelius** [comment] 2019-01-10 17:09
I like the idea of relay.config.js using https://github.com/davidtheclark/cosmiconfig, metro bundler uses it

https://github.com/facebook/metro/blob/master/packages/metro-config/src/loadConfig.js#L60

**Comment by ckknight** [comment] 2019-01-10 19:09
@josephsavona I'm working with 30+ custom scalars. Seems like that'd get a bit hairy rather quickly. It'd be a stopgap that I'd prefer over what I'm currently doing.

**Comment by josephsavona** [comment] 2019-01-11 16:16
@ckknight Ah, yeah with that many custom scalars command line flags would get annoying quickly. Maybe not that then.

**Closed** 2019-06-11 18:31 UTC

**Comment by ckknight** [comment] 2019-06-18 17:11
Thanks so much for your effort on this, @alloy

**Comment by alloy** [comment] 2019-06-18 19:36
You got it 👍

**Comment by gothraven** [comment] 2019-11-11 21:43
This is the first issue on google when we look for how to use custom scalars with Relay, I have read through all the comments and the commit messages but still I have no idea how to solve this 😅 can anyone write a simple steps solutions ?

I tried creating a `relay.config.json` `relay.config.js` in `./src` in the root of the project
I even tried adding the customScalars to the Cli but nothing changed
