### ISSUE TITLE
`hasOptimisticUpdate` returns `true` after mutation is applied

### ISSUE THREAD

**Issue by barbuza** [facebook/relay#86] opened 2015-08-17 00:25 UTC
`hasOptimisticUpdate` returns true after mutation is applied if optimistic update data equals to real one. easy to get this behaviour in provided `relay-treasurehunt` example by adding `hasTreasure: false` to `hidingSpot` in `CheckHidingSpotForTreasureMutation.getOptimisticResponse`

**Comment by yuzhi** [comment] 2015-08-17 01:52
Thanks for reporting this. This is mainly caused by not triggering an render when the optimistic node is no longer optimistic. We are aware of this and will be fixing it soon.

**Comment by yungsters** [comment] 2015-10-15 04:54
This was fixed by 3e27531d20087510db8747cb708682efb24acef5.

**Closed by yungsters** 2015-10-15 04:54 UTC
Labels: bug
