### ISSUE TITLE
The Generated @refetchable query require('...')  has no .js file extension

### ISSUE THREAD

**Issue by babangsund** [facebook/relay#2844] opened 2019-09-09 21:18 UTC
I was playing around with the `relay-experimental` package when I stumbled upon an issue.
I'm fully aware it isn't ready yet, however this did seem like an issue to me. 😅 

Assuming the query:
```graphql
fragment ViewerFragment on Viewer @refetchable(queryName: "ViewerFragmentRefetchQuery") {
    id
    name
}
```
The `__generated__/ViewerFragmentRefetchQuery.graphql.js` file is then generated.
(Assuming the WriterConfig.extension hasn't been altered)

By using the [CodeMarker.moduleDependency](https://github.com/facebook/relay/blob/c203d54e75d71e0ca1c2c3c8385f7814a5729dfe/packages/relay-compiler/util/CodeMarker.js#L16) method, https://github.com/facebook/relay/blob/cf5566eb0fbee1f75f821d27ad738c23788cea6c/packages/relay-compiler/codegen/ReaderCodeGenerator.js#L76 the moduleName is set to `ViewerFragmentRefetchQuery.graphql`, [seemingly to be extended with the configured file extension later on](https://github.com/facebook/relay/blob/c203d54e75d71e0ca1c2c3c8385f7814a5729dfe/packages/relay-compiler/codegen/writeRelayGeneratedFile.js#L73). (i.e. `.js`)

In the [printRequireModuleDependency](https://github.com/facebook/relay/blob/c203d54e75d71e0ca1c2c3c8385f7814a5729dfe/packages/relay-compiler/codegen/writeRelayGeneratedFile.js#L27) function however, https://github.com/facebook/relay/blob/c203d54e75d71e0ca1c2c3c8385f7814a5729dfe/packages/relay-compiler/codegen/writeRelayGeneratedFile.js#L28 the moduleName is only ever converted back to the original `.graphql` extended moduleName, neglecting the file extension.

This outputs `require('ViewerFragmentRefetchQuery.graphql')` rather than `require('./ViewerFragmentRefetchQuery.graphql.js')` which points to the generated refetch query file.

I'm thinking this is not intentional? 🤔

**Comment by mrtnzlml** [comment] 2019-09-09 21:21
@benashman Sounds like a duplicate of https://github.com/facebook/relay/issues/2713 maybe?

**Comment by babangsund** [comment] 2019-09-09 21:24
Oh yeah! My bad. 👍

**Comment by babangsund** [comment] 2019-09-09 21:31
Possible duplicate of https://github.com/facebook/relay/issues/2713

**Closed** 2019-09-09 21:31 UTC
