### ISSUE TITLE
pending optimistic updaters always run after local updaters

### ISSUE THREAD

**Issue by mattkrick** [facebook/relay#2481] opened 2018-06-26 18:43 UTC
Simplest scenario:
let's say `S0 = 1`
then, i optimistically update it `S1 = 2`
then, i update it locally `S2 = S1 * 2`

the result should be 4, not 2.

the culprit is here `RelayPublishQueue.prototype.run`:

```js
    this._commitData();
    this._commitUpdaters();
    this._applyUpdates();
    this._pendingBackupRebase = false;
    this._store.notify();
```

it's easy to see if you write it in transforms:
```js
T1 = (state) => 1
T2 = (state) => 2
T3 = (state) => state * 2
```

the publish queue is running `T1, T3, T2` that ain't right.

we should fix this before the client schema API leaves beta

**Comment by mattkrick** [comment] 2018-06-26 22:50
While attempting a PR, I noticed relay implicitly only supports convergent data types. Why is that?

I didn't see this documented anywhere, but it's pretty huge. That means the `updater` method CANNOT create a new value based off of the value in store. In real life, this is critical for computing things like cursor offsets (and client caches :wink:).

For example, let's say your updater is a transform:
updater = (state) => state < 0 ? state * -1 : state + 10
If the mutations don't return in order, your state is borked!
let's say the above is called with `1, -1, -1` (primes denote optimistic responses):

```
S0 = 0
S1' = S0 + 10 = 10
S1 = S0 + 10 = 10
S2' = S1 * -1  = -10
S2 = S1 * -1 = -10 
S3' = S2 * -1 = 10
S3 = S2 * -1 = 10
```

That's pretty great! But what if the 3rd mutation returns first?
```
S0 = 0
S1' = S0 + 10 = 10
S2' = S1' * -1 = -10
S3' = S2' * -1 = 10
S3 = ((S0 * -1) + 10) * -1 = -10 // uh oh! we applied S3, then S1' then S2'
S1 = (S3 + 10) * -1 = -10
S2 = S1 * -10 = -10
```
We ended up with the wrong answer!


I propose computing the transforms in order :
```
S0 = 0
S1' = S0 + 10 = 10
S2' = S1' * -1 = -10
S3' = S2' * -1 = 10
S3 = S2' * -1 = 10
S1 = (S0 + 10) * -1 * -1 = 10
S2 = S1 * -1 * -1 = 10
```

The reason I typed out all the boring math is so you can see that not only is this accurate, but it comes at no performance penalty (add up the `+,*` symbols in each approach). We're not increasing memory or CPU cycles, we're just changing the order of operations. This is exactly how it's done in https://github.com/mattkrick/redux-optimistic-ui/blob/master/src/index.js

**Comment by dminkovsky** [comment] 2018-07-07 17:14
> the culprit is here RelayPublishQueue.prototype.run:

This is a bug? Personally, I appreciate the semantics here. You have two different kinds of update: "commit" and "applies", the former mutates the store and does not record a backup, while the latter mutates the store and records a backup that you can then apply to undo the update. `.run()` enables these semantics.

So if you have an optimistic update and you commit a non-optimistic update on that same key, the semantics of these updates are that the optimistic update is reverted. I think that's what missing from:

> Simplest scenario:
> let's say S0 = 1
> then, i optimistically update it S1 = 2
> then, i update it locally S2 = S1 * 2
>
> the result should be 4, not 2.

if I am understanding this issue correctly.

**Comment by dminkovsky** [comment] 2018-07-07 17:17
I am stressing the semantics of the two different update type because they correlate exactly to things I want in my app: specifically the separation of "committed" and "uncommitted" state, with update linearization _within_ these two sets of state, but not across them. I really appreciate Relay is set up this way. I can accumulate dirty state separately from clean state, sync it remotely, and then mark it committed and throw away the dirty state.

**Comment by dminkovsky** [comment] 2018-07-08 00:53
Suppose:

* I have a node type `Message`. It has two fields: `to` and `body`.
* `MessageMutation` mutates the message. Its input object has two optional fields, `to` and `body`. You can submit the mutation with none, either or both fields.
* `MessageUpdater` handles UI events, updates Relay and syncs data remotely. 

Here is the abbreviated code: https://gist.github.com/dminkovsky/6c6022c9c40b579235c206cc92a2900c

As the user updates a message, I keep a single applied optimistic update for that message that contains the aggregated updates values for `to` and `body`. See `#update()`, where I either apply or replace.

When I am ready, I `#persist()`.

I really enjoy that I can keep accumulating updates while I `#persist()`. Upon a successful persist, I reverts the update that corresponded to that persist. I think this is quite nice and elegant. The current publish queue semantics and `#run()` implementation enable this.

I imagine the more scientifically sound approach would involve keeping an optimistic update for every user interaction, and then persist that linear series of updates remotely?

**Comment by dminkovsky** [comment] 2018-07-09 14:45
Indeed, I am not using a local schema, but I am not sure how using a local schema would help me. I would still need to JSON stringify before applying the body, because the body is a Draftjs structure.

I had never noticed `commitLocalUpdate`. Thanks for pointing it out. But I don't see how it helps me. All I'm seeing here is a wrapper around `environment.commitUpdate()`. This commits the updater to the store, but unlike `environment.applyUpdate()`, it does not record a backup in case this updater needs to be reverted. But that's exactly what I need: I need to apply updates to the store, but I also want to record a backup of that update so that I can backup rebase. The backup rebase is really nice. For me it seems to enable things like attempting to sync some optimistically applied state, allowing the user to apply or replace said optimistic state while it's remote syncing, and then easily figuring out what should be synced next if the sync fails or succeeds.  It's awkward that there's no API for examining the publish queue, which is why I went internal, but I was thinking either (i) the API would be honed and exposed, (ii) something better would replace the current system.

By the way, I am not using updater functions because I think it's more elegant to apply updates optimistically as proper payload-based updates, then sync those updates remotely and simply revert them from the store as the syncs succeed. You can do the same thing with updater functions, except updater functions are opaque in the sense that they're not associated with a particular operation selector (ie. an operation-fragment-variables). Since I apply optimistic updates as operation selector payloads, I can maintain a correlation between store state with operation variables, which is useful in some instances for me.

**Comment by mattkrick** [comment] 2018-07-09 22:04
> but I am not sure how using a local schema would help me here

honestly, you're overcomplicating something that's pretty simple: it's just 2 controlled inputs. there should only ever exist 1 optimistic update for 1 server update. if that's not the case, you're doing it wrong.
just try using local updates.

**Comment by dminkovsky** [comment] 2018-07-09 22:29
> there should only ever exist 1 optimistic update for 1 server update.

that's exactly what i have. did you read my reply? was it unclear?

**Comment by mattkrick** [comment] 2018-07-09 23:18
you're adding or replacing an optimistic update every time update is called. yes, you only have 1 at a time, but you're using relay internals to create & replace it multiple times before a single server mutation is even triggered. That's not great.

Let's use a simple example. You've got a basic input field & its state is stored in relay. you persist it to the server every 5 seconds so the user don't lose their progress. 
They're typing the word "Cat". They type a "C", then they type an "a", then they pause for 5 seconds, so it sends that off to the server, then they type "t", then the server replies with "Ca". If you accept the new state, then they those their "t". I _think_ that's the basic problem you're trying to solve.

S0 = ''
S1 = 'C'
S2 = 'Ca'
S3 = 'Cat'

Now let's break it into transforms (' denotes optimistic, * denotes local update)

T1* = (state) => state + 'C' 
T2* = (state) => state + 'a'
T2' = () => 'Ca' // 5 seconds is up! send it to the server
T3* = (state) => state + 't'
T2 = () => 'Ca' // server responded!

Using relay today, server data runs first, then local, then optimistic. Let's see how that plays out:

- T2' gets reverted
- T2 runs = 'Ca'
- Then T1* runs = ' CaC'
- Then T2* runs = 'Caca'
- Then T3* runs = 'CaCat'


Using my PR, let's see what happens:
- T2' gets replaced by T2
- T1 runs = 'C'
- T2* runs = 'Ca'
- T2 runs = 'Ca'
- T3 runs = 'Cat'

I really hope that makes sense!

**Comment by mattkrick** [comment] 2018-07-09 23:36
BONUS:
What I implemented is not new or novel. To learn more, you can read up on communicative data types:
https://github.com/ljwagerfield/crdt
http://jtfmumm.com/blog/2015/11/17/crdt-primer-1-defanging-order-theory/
http://digitalfreepen.com/2017/10/06/simple-real-time-collaborative-text-editor.html

The bulk of the PR is only ~200 LOCs: you seem to know your stuff about how the current publish queue works, so it should be pretty easy to grok: https://github.com/mattkrick/relay/blob/6b1196a52efccbc89d5743345c92aa779b61bca2/packages/relay-runtime/store/RelayPublishQueue.js

Alternatively, here's how optimistic updates are handled in redux in just 70 lines: https://github.com/mattkrick/redux-optimistic-ui/blob/master/src/index.js#L20-L93

**Comment by kassens** [comment] 2018-07-10 05:30
I need to find more time to read through all the comments here, but I think the current issue is in documentation rather then behavior.



- **commitUpdate** sends a mutation request to the server.
  - If it has an *optimistic update*, we use that to present a best guess to the client for a request that's still in flight to the server.
  - on *server response*, the optimistic update is dropped, we now apply the actual response to the client as source of truth
- **commitLocalUpdate:** just writes a value as source of truth. It can be used for client schema extensions or cases where maybe a non-GraphQL request was made to to update the server in some integration case with a legacy system.

Now, if a client sends 2 mutations to the server that are both increasing a counter, one +2 and another +3, these requests are both in flight the optimistic updates are stacked as +2, +3. If either of them returns, the optimistic changes are rolled back, the server response is applied as the source of truth and the other update is re-applied as the best guess on top of the new confirmed server value.

Now, there are situations where the end result depends on what is applied first. The easiest example is "set to 1" and "set to 2" mutations. If the client sends both of them in parallel, we might not even know what's the correct end result in case one mutation takes longer somewhere!

Relay Classic used to have a "mutation queue" and a "collision key" that queued up mutations that might change conflicting data. This didn't make it into the simplified modern impleentation as the "correct" solution really depends on the product. What if an intermediate mutation fails? Should subsequent mutations still apply? Should mutations in the middle maybe be dropped (could be useful if it's updating the most recent saved state)?

The hope here with the modern redesign was that the API offers enough primitives to build an abstraction on top of that. If you have a use case that queues up mutations in some way, maybe that could be expressed as a sharable utility module?

Sorry it's getting late, but I hope this helps folks here understand some of this design. We should see if we can incorporate some of this into the docs!

**Comment by mattkrick** [comment] 2018-07-10 15:11
hey @kassens thanks for the input!

Here's where there be dragons:

> If the client sends both of them in parallel, we might not even know what's the correct end result in case one mutation takes longer somewhere!

it's javascript, things don't happen in parallel, 1 thing always happens first. Even if 2 mutations are sent in the same batched payload, 1 will get called before the other, and as a front-end developer, I get to decide which! In my PR, that order is preserved. so if operation A' happens, then operation B', then operation B returns before operation A, you should apply A', then apply B, then when A returns, you can commit them both. ***No "best guess" needed!*** 

when you get the time, please check out PR #2482. feel free to reach out by email or video chat if you wanna discuss offline. I'll be in SF tomorrow & thursday if in-person is easier.

**Comment by kassens** [comment] 2018-07-10 16:11
Network requests do happen in parallel:
- send request A: set to "foo"
- send request B: set to "bar"
- request B returns with "value is bar now"
- request A returns with "value is foo now"
What is the real value in the end that the client should display? In Relay newer values override older values, but that might not be correct here. The only way to be sure is to wait with sending B when A completed.

**Comment by mattkrick** [comment] 2018-07-10 17:01
> The only way to be sure is to wait with sending B when A completed.

Not necessarily! You don't need to wait, you simply need to wait ***to commit***. Lamport's happened-before relation guarantees it.

> In Relay newer values override older values

Yes yes yes 100% yes. Relay has a built-in race condition. Now that we agree on that, let's kill it!

Using your example, here is how you fix it:

- send request A => apply A
- send request B => apply B
- request B returns => apply A, apply B
- request A returns -> commit A, commit B

Please continue to ask any questions or reach out if you'd like to do a live code review of #2482. Once you grok how it works, it'll make working with distributed systems much, much easier.

**Comment by dminkovsky** [comment] 2018-08-27 15:27
@mattkrick hey thanks for your feedback. I removed my comments to clean up the thread.

**Comment by mattkrick** [comment] 2018-08-27 21:37
@dminkovsky sounds good! if you like the PR feel free to make some noise on it, it's been stonewalled for a couple months now :disappointed:.

**Comment by josephsavona** [comment] 2019-02-01 23:54
I've replied extensively on the [associated PR](https://github.com/facebook/relay/pull/2482#issuecomment-459902082), so I'm going to close this issue just to consolidate discussion.

**Closed by josephsavona** 2019-02-01 23:54 UTC
