### ISSUE TITLE
Q: beforeSend hooks in DefaultNetworkLayer

### ISSUE THREAD

**Issue by keithpitt** [facebook/relay#48] opened 2015-08-13 04:40 UTC
Hey, so I'm playing around with Relay and I need to add an authentication token to all outgoing HTTP calls made by Relay. Is my only option to implement my own NetworkLayer?

Do you think it'd be useful to add a `beforeSend` type hook inside the layer so we can make changes to the requests before sending them off? In my case, I need to add a HTTP header.

Let me know if there's another place where I should be asking this question! Thanks!

**Comment by Tlvenn** [comment] 2015-08-13 13:01
More broadly the default network layer should be capable of handling interceptors that can manipulate both the request and the response.

**Comment by yungsters** [comment] 2015-08-13 18:10
The default network layer was intended to be a simple example for how to create your own. (In fact, I thought that not everyone would want to be using a `fetch` polyfill.) It really does not do all that much, so while I'm not opposed to making it more flexible, is there any particular reason you wouldn't want to simply create your own?

If there is something valuable in the default network layer that you really would not want to re-implement, maybe we should be exposing it in a way that custom network layers can re-use them.

If we think the best path is still to make the network layer more flexible, would it be sufficient to replace the second and third constructor arguments (`timeout` and `retryDelays`) with an fetch `init` argument that gets spread into the actual `init` that we pass (to either `fetch` or `fetchWithRetries`)?

**Comment by devknoll** [comment] 2015-08-13 18:58
I'm not so sure about interceptors for request/response (though these may be good for dev tools - but a dev tool could also probably just implement its own proxying network layer, right?) but I think that some way to add headers is probably the last thing the default network layer needs to truly become a default. It seems like a common enough use case.

`init` seems like it might be a good compromise.

**Comment by yungsters** [comment] 2015-08-14 05:50
> though these may be good for dev tools - but a dev tool could also probably just implement its own proxying network layer, right?

Yup, see #60. Alternatively, a man-in-the-middle network layer could be used for this:

```
Relay.injectNetworkLayer({
  ...defaultNetworkLayer,
  sendQueries(queryRequests) {
    // Sniff, sniff.
    return defaultNetworkLayer.sendQueries(queryRequests);
  },
  sendMutation(mutationRequest) {
    // Sniff, sniff.
    return defaultNetworkLayer.sendMutation(mutationRequest);
  },
});
```

**Comment by yungsters** [comment] 2015-08-14 06:54
We're trying to maintain good GitHub hygiene, so I'm going to close this out in favor of #70. Feel free to continue discussion there.

**Closed by yungsters** 2015-08-14 06:54 UTC
Labels: question

**Comment by keithpitt** [comment] 2015-08-14 16:45
That's great! That PR solves my problem. Thanks for that!! :heart:
